/* Generated By:JavaCC: Do not edit this line. CreoleWikiScannerTokenManager.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.creole.javacc;
import org.wikimodel.wem.WikiStyle;
import org.wikimodel.wem.impl.IWikiScannerContext;
import org.wikimodel.wem.IWemConstants;

public class CreoleWikiScannerTokenManager implements CreoleWikiScannerConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjMoveStringLiteralDfa0_0()
{
   return jjMoveNfa_0(17, 0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 141;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 17:
                  if ((0x3ff0000ffffd9ffL & l) != 0L)
                  {
                     if (kind > 70)
                        kind = 70;
                     jjCheckNAdd(97);
                  }
                  else if ((0xfc00fffe00000000L & l) != 0L)
                  {
                     if (kind > 71)
                        kind = 71;
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 68)
                        kind = 68;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x100000200L & l) != 0L)
                  {
                     if (kind > 69)
                        kind = 69;
                     jjCheckNAdd(96);
                  }
                  if (curChar == 13)
                     jjAddStates(5, 10);
                  else if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 37;
                  else if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 35;
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 33;
                  else if (curChar == 61)
                  {
                     if (kind > 63)
                        kind = 63;
                     jjstateSet[jjnewStateCnt++] = 24;
                  }
                  break;
               case 2:
               case 10:
                  jjCheckNAddStates(11, 16);
                  break;
               case 3:
                  if (curChar == 10)
                     jjCheckNAdd(9);
                  break;
               case 5:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 6:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAdd(9);
                  break;
               case 9:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 20:
               case 21:
                  jjCheckNAddStates(17, 19);
                  break;
               case 23:
                  if (curChar != 61)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 24:
                  if (curChar != 61)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddStates(20, 23);
                  break;
               case 25:
                  if (curChar == 61 && kind > 63)
                     kind = 63;
                  break;
               case 26:
                  if (curChar != 61)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(25);
                  break;
               case 27:
                  if (curChar != 61)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddTwoStates(25, 26);
                  break;
               case 28:
                  if (curChar != 61)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddStates(24, 26);
                  break;
               case 30:
                  if (curChar == 61 && kind > 64)
                     kind = 64;
                  break;
               case 33:
                  if (curChar == 47 && kind > 66)
                     kind = 66;
                  break;
               case 34:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if (curChar == 42 && kind > 66)
                     kind = 66;
                  break;
               case 36:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 35 && kind > 66)
                     kind = 66;
                  break;
               case 38:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 40:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(40, 41);
                  break;
               case 41:
                  if (curChar == 58)
                     jjAddStates(27, 31);
                  break;
               case 43:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(43, 41);
                  break;
               case 44:
                  if (curChar != 47)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(32, 39);
                  break;
               case 45:
                  if ((0x2fff7fd200000000L & l) != 0L)
                     jjCheckNAddStates(40, 42);
                  break;
               case 46:
                  if (curChar == 37)
                     jjCheckNAdd(47);
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(40, 42);
                  break;
               case 50:
                  if (curChar == 37)
                     jjCheckNAdd(51);
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(43, 48);
                  break;
               case 53:
                  if ((0x2bff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(43, 48);
                  break;
               case 54:
                  if (curChar == 58)
                     jjCheckNAdd(55);
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(49, 52);
                  break;
               case 56:
                  if (curChar != 47)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(53, 57);
                  break;
               case 57:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(53, 57);
                  break;
               case 58:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(53, 57);
                  break;
               case 61:
                  if (curChar != 63)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(58, 60);
                  break;
               case 62:
                  if ((0xafffffd200000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(58, 60);
                  break;
               case 63:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(58, 60);
                  break;
               case 66:
                  if (curChar != 35)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddTwoStates(67, 68);
                  break;
               case 67:
                  if ((0xafffffd200000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddTwoStates(67, 68);
                  break;
               case 68:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 70:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddTwoStates(67, 68);
                  break;
               case 71:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(47, 51);
                  break;
               case 72:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 73:
                  if (curChar != 47)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(61, 64);
                  break;
               case 74:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(65, 69);
                  break;
               case 75:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(65, 69);
                  break;
               case 78:
                  if (curChar != 47)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(70, 74);
                  break;
               case 79:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(70, 74);
                  break;
               case 80:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 81:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 82:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(70, 74);
                  break;
               case 83:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 84:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(86, 89);
                  break;
               case 86:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 87:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 88:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(75, 79);
                  break;
               case 89:
                  if ((0x2bff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(75, 79);
                  break;
               case 90:
                  if (curChar != 47)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(80, 84);
                  break;
               case 91:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(80, 84);
                  break;
               case 92:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 93:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 94:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(80, 84);
                  break;
               case 95:
                  if ((0x2bff7fd200000000L & l) != 0L)
                     jjCheckNAddTwoStates(86, 89);
                  break;
               case 96:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAdd(96);
                  break;
               case 97:
                  if ((0x3ff0000ffffd9ffL & l) == 0L)
                     break;
                  if (kind > 70)
                     kind = 70;
                  jjCheckNAdd(97);
                  break;
               case 98:
                  if ((0xfc00fffe00000000L & l) != 0L && kind > 71)
                     kind = 71;
                  break;
               case 99:
                  if (curChar == 13)
                     jjAddStates(5, 10);
                  break;
               case 100:
                  if (curChar == 10)
                     jjCheckNAdd(101);
                  break;
               case 101:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(101, 102);
                  break;
               case 102:
                  if ((0x40800000000L & l) != 0L)
                     jjCheckNAdd(103);
                  break;
               case 103:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAdd(103);
                  break;
               case 104:
                  if (curChar == 10)
                     jjCheckNAdd(105);
                  break;
               case 106:
                  if (curChar == 61 && kind > 57)
                     kind = 57;
                  break;
               case 107:
                  if (curChar == 10)
                     jjCheckNAdd(108);
                  break;
               case 108:
                  if (curChar != 61)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAddTwoStates(109, 110);
                  break;
               case 109:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAdd(109);
                  break;
               case 110:
                  if (curChar != 61)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAddStates(85, 89);
                  break;
               case 111:
                  if (curChar != 61)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAdd(109);
                  break;
               case 112:
                  if (curChar != 61)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAddTwoStates(111, 109);
                  break;
               case 113:
                  if (curChar != 61)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAddStates(90, 92);
                  break;
               case 114:
                  if (curChar != 61)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAddStates(93, 96);
                  break;
               case 115:
                  if (curChar == 10)
                     jjCheckNAdd(133);
                  break;
               case 118:
               case 126:
                  jjCheckNAddStates(97, 102);
                  break;
               case 119:
                  if (curChar == 10)
                     jjCheckNAdd(125);
                  break;
               case 121:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 122:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAdd(125);
                  break;
               case 125:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 134:
                  if (curChar == 10)
                     jjCheckNAdd(138);
                  break;
               case 135:
                  if (curChar == 45)
                     jjCheckNAdd(136);
                  break;
               case 136:
                  if (curChar != 45)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(136);
                  break;
               case 137:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 138:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 139:
                  if (curChar == 10 && kind > 68)
                     kind = 68;
                  break;
               case 140:
                  if ((0x2400L & l) == 0L)
                     break;
                  if (kind > 68)
                     kind = 68;
                  jjCheckNAddStates(0, 4);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 17:
                  if ((0x87fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 70)
                        kind = 70;
                     jjCheckNAdd(97);
                  }
                  else if ((0x78000001f8000001L & l) != 0L)
                  {
                     if (kind > 71)
                        kind = 71;
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(40, 41);
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 31;
                  else if (curChar == 124)
                  {
                     if (kind > 64)
                        kind = 64;
                     jjstateSet[jjnewStateCnt++] = 30;
                  }
                  else if (curChar == 91)
                     jjCheckNAddStates(17, 19);
                  else if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 0:
                  if (curChar == 123)
                     jjCheckNAddStates(11, 16);
                  break;
               case 1:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 2:
                  jjCheckNAddStates(11, 16);
                  break;
               case 4:
                  if (curChar == 125)
                     jjCheckNAddStates(11, 16);
                  break;
               case 7:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 8:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 10:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(11, 16);
                  break;
               case 11:
               case 13:
                  if (curChar == 125)
                     jjCheckNAdd(10);
                  break;
               case 12:
                  if (curChar == 125)
                     jjAddStates(103, 104);
                  break;
               case 14:
                  if (curChar == 125 && kind > 61)
                     kind = 61;
                  break;
               case 15:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 18:
                  if (curChar == 91)
                     jjCheckNAddStates(17, 19);
                  break;
               case 19:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 20:
                  jjCheckNAddStates(17, 19);
                  break;
               case 21:
                  if ((0xffffffffdfffffffL & l) != 0L)
                     jjCheckNAddStates(17, 19);
                  break;
               case 22:
                  if (curChar == 93 && kind > 62)
                     kind = 62;
                  break;
               case 29:
                  if (curChar != 124)
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 31:
                  if (curChar == 92 && kind > 65)
                     kind = 65;
                  break;
               case 32:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 39:
               case 40:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(40, 41);
                  break;
               case 42:
               case 43:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(43, 41);
                  break;
               case 45:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(40, 42);
                  break;
               case 47:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(40, 42);
                  break;
               case 49:
                  if (curChar != 64)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(43, 48);
                  break;
               case 51:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 52:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(43, 48);
                  break;
               case 53:
                  if ((0x47fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(43, 48);
                  break;
               case 57:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(53, 57);
                  break;
               case 59:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 60:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(53, 57);
                  break;
               case 62:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(58, 60);
                  break;
               case 64:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(58, 60);
                  break;
               case 67:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddTwoStates(67, 68);
                  break;
               case 69:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 70:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddTwoStates(67, 68);
                  break;
               case 74:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(65, 69);
                  break;
               case 76:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 77:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(65, 69);
                  break;
               case 79:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(70, 74);
                  break;
               case 81:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 82:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(70, 74);
                  break;
               case 84:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(86, 89);
                  break;
               case 87:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 88:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(75, 79);
                  break;
               case 89:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(75, 79);
                  break;
               case 91:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(80, 84);
                  break;
               case 93:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 94:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 67)
                     kind = 67;
                  jjCheckNAddStates(80, 84);
                  break;
               case 95:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(86, 89);
                  break;
               case 97:
                  if ((0x87fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 70)
                     kind = 70;
                  jjCheckNAdd(97);
                  break;
               case 98:
                  if ((0x78000001f8000001L & l) != 0L && kind > 71)
                     kind = 71;
                  break;
               case 105:
                  if (curChar != 124)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 116:
                  if (curChar == 123)
                     jjCheckNAddStates(97, 102);
                  break;
               case 117:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 118:
                  jjCheckNAddStates(97, 102);
                  break;
               case 120:
                  if (curChar == 125)
                     jjCheckNAddStates(97, 102);
                  break;
               case 123:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 124:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 126:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(97, 102);
                  break;
               case 127:
               case 129:
                  if (curChar == 125)
                     jjCheckNAdd(126);
                  break;
               case 128:
                  if (curChar == 125)
                     jjAddStates(105, 106);
                  break;
               case 130:
                  if (curChar == 125 && kind > 59)
                     kind = 59;
                  break;
               case 131:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 133:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 17:
               case 97:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 70)
                     kind = 70;
                  jjCheckNAdd(97);
                  break;
               case 2:
               case 10:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(11, 16);
                  break;
               case 20:
               case 21:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(17, 19);
                  break;
               case 118:
               case 126:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(97, 102);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 141 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private final int jjMoveStringLiteralDfa0_1()
{
   return jjMoveNfa_1(4, 0);
}
private final int jjMoveNfa_1(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 142;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 4:
                  if ((0x3ff0000ffffd9ffL & l) != 0L)
                  {
                     if (kind > 54)
                        kind = 54;
                     jjCheckNAdd(74);
                  }
                  else if ((0xfc00fffe00000000L & l) != 0L)
                  {
                     if (kind > 55)
                        kind = 55;
                  }
                  else if ((0x100000200L & l) != 0L)
                  {
                     if (kind > 53)
                        kind = 53;
                     jjCheckNAddStates(107, 109);
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 52)
                        kind = 52;
                     jjCheckNAddStates(110, 114);
                  }
                  if (curChar == 61)
                  {
                     if (kind > 42)
                        kind = 42;
                     jjCheckNAddStates(115, 117);
                  }
                  else if (curChar == 13)
                     jjAddStates(118, 123);
                  else if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 13;
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 11;
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 0:
                  if (curChar == 45)
                     jjCheckNAdd(1);
                  break;
               case 1:
                  if (curChar != 45)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 3:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 6:
               case 7:
                  jjCheckNAddStates(124, 126);
                  break;
               case 11:
                  if (curChar == 47 && kind > 50)
                     kind = 50;
                  break;
               case 12:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 42 && kind > 50)
                     kind = 50;
                  break;
               case 14:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 35 && kind > 50)
                     kind = 50;
                  break;
               case 16:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 18:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  break;
               case 19:
                  if (curChar == 58)
                     jjAddStates(127, 131);
                  break;
               case 21:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(21, 19);
                  break;
               case 22:
                  if (curChar != 47)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(132, 139);
                  break;
               case 23:
                  if ((0x2fff7fd200000000L & l) != 0L)
                     jjCheckNAddStates(140, 142);
                  break;
               case 24:
                  if (curChar == 37)
                     jjCheckNAdd(25);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(140, 142);
                  break;
               case 28:
                  if (curChar == 37)
                     jjCheckNAdd(29);
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(143, 148);
                  break;
               case 31:
                  if ((0x2bff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(143, 148);
                  break;
               case 32:
                  if (curChar == 58)
                     jjCheckNAdd(33);
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(149, 152);
                  break;
               case 34:
                  if (curChar != 47)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(153, 157);
                  break;
               case 35:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(153, 157);
                  break;
               case 36:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(153, 157);
                  break;
               case 39:
                  if (curChar != 63)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(158, 160);
                  break;
               case 40:
                  if ((0xafffffd200000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(158, 160);
                  break;
               case 41:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(158, 160);
                  break;
               case 44:
                  if (curChar != 35)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddTwoStates(45, 46);
                  break;
               case 45:
                  if ((0xafffffd200000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddTwoStates(45, 46);
                  break;
               case 46:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddTwoStates(45, 46);
                  break;
               case 49:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(25, 29);
                  break;
               case 50:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 51:
                  if (curChar != 47)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(161, 164);
                  break;
               case 52:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(165, 169);
                  break;
               case 53:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(165, 169);
                  break;
               case 56:
                  if (curChar != 47)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(170, 174);
                  break;
               case 57:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(170, 174);
                  break;
               case 58:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(170, 174);
                  break;
               case 61:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(64, 67);
                  break;
               case 64:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(175, 179);
                  break;
               case 67:
                  if ((0x2bff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(175, 179);
                  break;
               case 68:
                  if (curChar != 47)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(180, 184);
                  break;
               case 69:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(180, 184);
                  break;
               case 70:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 72:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(180, 184);
                  break;
               case 73:
                  if ((0x2bff7fd200000000L & l) != 0L)
                     jjCheckNAddTwoStates(64, 67);
                  break;
               case 74:
                  if ((0x3ff0000ffffd9ffL & l) == 0L)
                     break;
                  if (kind > 54)
                     kind = 54;
                  jjCheckNAdd(74);
                  break;
               case 75:
                  if ((0xfc00fffe00000000L & l) != 0L && kind > 55)
                     kind = 55;
                  break;
               case 76:
                  if (curChar == 13)
                     jjAddStates(118, 123);
                  break;
               case 77:
                  if (curChar == 10)
                     jjCheckNAdd(78);
                  break;
               case 78:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(78, 79);
                  break;
               case 79:
                  if ((0x40800000000L & l) != 0L)
                     jjCheckNAdd(80);
                  break;
               case 80:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 40)
                     kind = 40;
                  jjCheckNAdd(80);
                  break;
               case 81:
                  if (curChar == 10)
                     jjCheckNAdd(82);
                  break;
               case 83:
                  if (curChar == 61 && kind > 41)
                     kind = 41;
                  break;
               case 84:
                  if (curChar == 10)
                     jjCheckNAdd(85);
                  break;
               case 85:
                  if (curChar != 61)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAddTwoStates(86, 87);
                  break;
               case 86:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAdd(86);
                  break;
               case 87:
                  if (curChar != 61)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAddStates(185, 189);
                  break;
               case 88:
                  if (curChar != 61)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAdd(86);
                  break;
               case 89:
                  if (curChar != 61)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAddTwoStates(88, 86);
                  break;
               case 90:
                  if (curChar != 61)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAddStates(190, 192);
                  break;
               case 91:
                  if (curChar != 61)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAddStates(193, 196);
                  break;
               case 92:
                  if (curChar == 10)
                     jjCheckNAdd(110);
                  break;
               case 95:
               case 103:
                  jjCheckNAddStates(197, 202);
                  break;
               case 96:
                  if (curChar == 10)
                     jjCheckNAdd(102);
                  break;
               case 98:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 99:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAdd(102);
                  break;
               case 102:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 111:
                  if (curChar == 10)
                     jjCheckNAdd(3);
                  break;
               case 112:
                  if (curChar == 10 && kind > 52)
                     kind = 52;
                  break;
               case 113:
                  if ((0x2400L & l) == 0L)
                     break;
                  if (kind > 52)
                     kind = 52;
                  jjCheckNAddStates(110, 114);
                  break;
               case 114:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(107, 109);
                  break;
               case 115:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAdd(115);
                  break;
               case 117:
                  if (curChar == 61 && kind > 48)
                     kind = 48;
                  break;
               case 118:
                  if (curChar != 61)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAddStates(115, 117);
                  break;
               case 119:
                  if (curChar != 61)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddStates(203, 206);
                  break;
               case 120:
                  if (curChar == 61 && kind > 47)
                     kind = 47;
                  break;
               case 121:
                  if (curChar != 61)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAdd(120);
                  break;
               case 122:
                  if (curChar != 61)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddTwoStates(120, 121);
                  break;
               case 123:
                  if (curChar != 61)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddStates(207, 209);
                  break;
               case 127:
               case 135:
                  jjCheckNAddStates(210, 215);
                  break;
               case 128:
                  if (curChar == 10)
                     jjCheckNAdd(134);
                  break;
               case 130:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 131:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAdd(134);
                  break;
               case 134:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 4:
                  if ((0x87fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 54)
                        kind = 54;
                     jjCheckNAdd(74);
                  }
                  else if ((0x78000001f8000001L & l) != 0L)
                  {
                     if (kind > 55)
                        kind = 55;
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  else if (curChar == 123)
                     jjCheckNAddTwoStates(109, 141);
                  else if (curChar == 124)
                  {
                     if (kind > 41)
                        kind = 41;
                     jjCheckNAddTwoStates(83, 117);
                  }
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 9;
                  else if (curChar == 91)
                     jjCheckNAddStates(124, 126);
                  break;
               case 5:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
                  jjCheckNAddStates(124, 126);
                  break;
               case 7:
                  if ((0xffffffffdfffffffL & l) != 0L)
                     jjCheckNAddStates(124, 126);
                  break;
               case 8:
                  if (curChar == 93 && kind > 46)
                     kind = 46;
                  break;
               case 9:
                  if (curChar == 92 && kind > 49)
                     kind = 49;
                  break;
               case 10:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 17:
               case 18:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  break;
               case 20:
               case 21:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(21, 19);
                  break;
               case 23:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(140, 142);
                  break;
               case 25:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 26:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(140, 142);
                  break;
               case 27:
                  if (curChar != 64)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(143, 148);
                  break;
               case 29:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 30:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(143, 148);
                  break;
               case 31:
                  if ((0x47fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(143, 148);
                  break;
               case 35:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(153, 157);
                  break;
               case 37:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(153, 157);
                  break;
               case 40:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(158, 160);
                  break;
               case 42:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 43:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(158, 160);
                  break;
               case 45:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddTwoStates(45, 46);
                  break;
               case 47:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddTwoStates(45, 46);
                  break;
               case 52:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(165, 169);
                  break;
               case 54:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 55:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(165, 169);
                  break;
               case 57:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(170, 174);
                  break;
               case 59:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 60:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(170, 174);
                  break;
               case 62:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(64, 67);
                  break;
               case 65:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 66:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(175, 179);
                  break;
               case 67:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(175, 179);
                  break;
               case 69:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(180, 184);
                  break;
               case 71:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 72:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 51)
                     kind = 51;
                  jjCheckNAddStates(180, 184);
                  break;
               case 73:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(64, 67);
                  break;
               case 74:
                  if ((0x87fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 54)
                     kind = 54;
                  jjCheckNAdd(74);
                  break;
               case 75:
                  if ((0x78000001f8000001L & l) != 0L && kind > 55)
                     kind = 55;
                  break;
               case 82:
                  if (curChar != 124)
                     break;
                  if (kind > 41)
                     kind = 41;
                  jjCheckNAdd(83);
                  break;
               case 93:
                  if (curChar == 123)
                     jjCheckNAddStates(197, 202);
                  break;
               case 94:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 95:
                  jjCheckNAddStates(197, 202);
                  break;
               case 97:
                  if (curChar == 125)
                     jjCheckNAddStates(197, 202);
                  break;
               case 100:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 101:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 103:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(197, 202);
                  break;
               case 104:
               case 106:
                  if (curChar == 125)
                     jjCheckNAdd(103);
                  break;
               case 105:
                  if (curChar == 125)
                     jjAddStates(216, 217);
                  break;
               case 107:
                  if (curChar == 125 && kind > 43)
                     kind = 43;
                  break;
               case 108:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 110:
                  if (curChar == 123)
                     jjCheckNAdd(109);
                  break;
               case 116:
                  if (curChar != 124)
                     break;
                  if (kind > 41)
                     kind = 41;
                  jjCheckNAddTwoStates(83, 117);
                  break;
               case 124:
                  if (curChar == 123)
                     jjCheckNAddTwoStates(109, 141);
                  break;
               case 125:
                  if (curChar == 123)
                     jjCheckNAddStates(210, 215);
                  break;
               case 126:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 127:
                  jjCheckNAddStates(210, 215);
                  break;
               case 129:
                  if (curChar == 125)
                     jjCheckNAddStates(210, 215);
                  break;
               case 132:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 133:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 135:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(210, 215);
                  break;
               case 136:
               case 138:
                  if (curChar == 125)
                     jjCheckNAdd(135);
                  break;
               case 137:
                  if (curChar == 125)
                     jjAddStates(218, 219);
                  break;
               case 139:
                  if (curChar == 125 && kind > 45)
                     kind = 45;
                  break;
               case 140:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 4:
               case 74:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 54)
                     kind = 54;
                  jjCheckNAdd(74);
                  break;
               case 6:
               case 7:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(124, 126);
                  break;
               case 95:
               case 103:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(197, 202);
                  break;
               case 127:
               case 135:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(210, 215);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 142 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   101, 105, 108, 133, 138, 100, 104, 107, 115, 134, 139, 1, 5, 6, 10, 11, 
   12, 19, 21, 22, 25, 26, 27, 28, 25, 26, 27, 42, 72, 73, 83, 95, 
   45, 49, 53, 54, 56, 61, 66, 71, 46, 45, 49, 50, 53, 54, 56, 61, 
   66, 55, 56, 61, 66, 56, 57, 58, 61, 66, 62, 63, 66, 74, 75, 61, 
   66, 74, 75, 78, 61, 66, 78, 79, 80, 61, 66, 86, 89, 90, 61, 66, 
   90, 91, 92, 61, 66, 111, 109, 112, 113, 114, 111, 109, 112, 111, 109, 112, 
   113, 117, 121, 122, 126, 127, 128, 13, 15, 129, 131, 78, 79, 115, 78, 82, 
   85, 110, 3, 86, 119, 87, 77, 81, 84, 92, 111, 112, 5, 7, 8, 20, 
   50, 51, 61, 73, 23, 27, 31, 32, 34, 39, 44, 49, 24, 23, 27, 28, 
   31, 32, 34, 39, 44, 33, 34, 39, 44, 34, 35, 36, 39, 44, 40, 41, 
   44, 52, 53, 39, 44, 52, 53, 56, 39, 44, 56, 57, 58, 39, 44, 64, 
   67, 68, 39, 44, 68, 69, 70, 39, 44, 88, 86, 89, 90, 91, 88, 86, 
   89, 88, 86, 89, 90, 94, 98, 99, 103, 104, 105, 120, 121, 122, 123, 120, 
   121, 122, 126, 130, 131, 135, 136, 137, 106, 108, 138, 140, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default : 
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
   "INITIAL_CONTEXT", 
};
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[142];
private final int[] jjstateSet = new int[284];
StringBuffer image;
int jjimageLen;
int lengthOfMatch;
protected char curChar;
public CreoleWikiScannerTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public CreoleWikiScannerTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 142; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 2 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   if (jjmatchedPos < 0)
   {
      if (image == null)
         t.image = "";
      else
         t.image = image.toString();
      t.beginLine = t.endLine = input_stream.getBeginLine();
      t.beginColumn = t.endColumn = input_stream.getBeginColumn();
   }
   else
   {
      String im = jjstrLiteralImages[jjmatchedKind];
      t.image = (im == null) ? input_stream.GetImage() : im;
      t.beginLine = input_stream.getBeginLine();
      t.beginColumn = input_stream.getBeginColumn();
      t.endLine = input_stream.getEndLine();
      t.endColumn = input_stream.getEndColumn();
   }
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = null;
   jjimageLen = 0;

   switch(curLexState)
   {
     case 0:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       jjmatchedKind = 52;
       jjmatchedPos = -1;
       curPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
           matchedToken = jjFillToken();
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default : 
         break;
   }
}
}
