/* Generated By:JavaCC: Do not edit this line. CommonWikiScannerConstants.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.common.javacc;

public interface CommonWikiScannerConstants {

  int EOF = 0;
  int INTERNAL_VERBATIM_START = 1;
  int INTERNAL_VERBATIM_END = 2;
  int INTERNAL_VERBATIM_CONTENT = 3;
  int INTERNAL_MACRO_START = 4;
  int INTERNAL_MACRO_END = 5;
  int INTERNAL_MACRO_CONTENT = 6;
  int LI_COMMON = 7;
  int DL = 8;
  int LIST_ITEM = 9;
  int PROPERTY = 10;
  int PROPERTY_DOC = 11;
  int DOC_BEGIN = 12;
  int DOC_END = 13;
  int VERBATIM_START = 14;
  int VERBATIM_END = 15;
  int ESCAPED = 16;
  int VERBATIM_CONTENT = 17;
  int MACRO_START = 18;
  int MACRO_END = 19;
  int MACRO_CONTENT = 20;
  int INFO = 21;
  int EXTENSION = 22;
  int PARAMS = 23;
  int HEADER = 24;
  int BR = 25;
  int ESCAPE = 26;
  int VERBATIM_INLINE = 27;
  int REFERENCE = 28;
  int HORLINE = 29;
  int CELL = 30;
  int QUOT_BLOCK = 31;
  int QUOT_LINE = 32;
  int FORMAT_SYMBOL = 33;
  int SPECIAL_SYMBOLS = 34;
  int NEW_LINE = 35;
  int SPACE = 36;
  int SPECIAL_SYMBOL = 37;
  int CHAR = 38;
  int URI = 39;
  int ALPHA = 40;
  int DIGIT = 41;
  int HEXDIG = 42;
  int URI_GEN_DELIMS = 43;
  int URI_SUB_DELIMS = 44;
  int URI_UNRESERVED = 45;
  int URI_RESERVED = 46;
  int URI_SCHEME = 47;
  int URI_PCT_ENCODED = 48;
  int URI_PCHAR = 49;
  int URI_QUERY = 50;
  int URI_FRAGMENT = 51;
  int URI_HIER_PART = 52;
  int URI_AUTHORITY = 53;
  int URI_USERINFO = 54;
  int URI_PATH_ABEMPTY = 55;
  int URI_PATH_ABSOLUTE = 56;
  int URI_PATH_ROOTLESS = 57;
  int URI_SEGMENT = 58;
  int URI_SEGMENT_NZ = 59;
  int URI_SEGMENT_NZ_NC = 60;
  int URI_PORT = 61;
  int URI_HOST = 62;
  int URI_REG_NAME = 63;
  int I_DOC_BEGIN = 64;
  int I_DOC_END = 65;
  int I_BR = 66;
  int I_ESCAPE = 67;
  int I_HORLINE = 68;
  int I_TABLE_ROW = 69;
  int I_TABLE_CELL = 70;
  int I_LIST_ITEM = 71;
  int I_VERBATIM_INLINE = 72;
  int I_VERBATIM_START = 73;
  int I_MACRO_BLOCK_START = 74;
  int I_MACRO_INLINE_START = 75;
  int I_QUOT_BLOCK = 76;
  int I_QUOT_LINE = 77;
  int I_INFO = 78;
  int I_EXTENSION_BLOCK = 79;
  int I_EXTENSION_INLINE = 80;
  int I_PROPERTY = 81;
  int I_PROPERTY_DOC = 82;
  int I_PROPERTY_INLINE = 83;
  int I_HEADER_BEGIN = 84;
  int I_REFERENCE = 85;
  int I_HEADER_END = 86;
  int I_FORMAT_SYMBOL = 87;
  int I_BLOCK_PARAMS = 88;
  int I_SPECIAL_SYMBOLS = 89;
  int I_URI = 90;
  int I_NL = 91;
  int I_SPACE = 92;
  int I_WORD = 93;
  int I_SPECIAL_SYMBOL = 94;
  int D_DOC_BEGIN = 95;
  int D_DOC_END = 96;
  int D_BR = 97;
  int D_ESCAPE = 98;
  int D_HORLINE = 99;
  int D_TABLE_ROW = 100;
  int D_TABLE_CELL = 101;
  int D_LIST_ITEM = 102;
  int D_VERBATIM_INLINE = 103;
  int D_VERBATIM_START = 104;
  int D_MACRO_BLOCK_START = 105;
  int D_MACRO_INLINE_START = 106;
  int D_QUOT_BLOCK = 107;
  int D_QUOT_LINE = 108;
  int D_INFO = 109;
  int D_EXTENSION_BLOCK = 110;
  int D_EXTENSION_INLINE = 111;
  int D_PROPERTY = 112;
  int D_PROPERTY_DOC = 113;
  int D_PROPERTY_INLINE = 114;
  int D_HEADER_BEGIN = 115;
  int D_REFERENCE = 116;
  int D_HEADER_END = 117;
  int D_FORMAT_SYMBOL = 118;
  int D_BLOCK_PARAMS = 119;
  int D_SPECIAL_SYMBOLS = 120;
  int D_URI = 121;
  int D_NL = 122;
  int D_SPACE = 123;
  int D_WORD = 124;
  int D_SPECIAL_SYMBOL = 125;

  int VERBATIM_CONTEXT = 0;
  int MACRO_CONTEXT = 1;
  int DEFAULT = 2;
  int INITIAL_CONTEXT = 3;

  String[] tokenImage = {
    "<EOF>",
    "<INTERNAL_VERBATIM_START>",
    "<INTERNAL_VERBATIM_END>",
    "<INTERNAL_VERBATIM_CONTENT>",
    "<INTERNAL_MACRO_START>",
    "<INTERNAL_MACRO_END>",
    "<INTERNAL_MACRO_CONTENT>",
    "<LI_COMMON>",
    "<DL>",
    "<LIST_ITEM>",
    "<PROPERTY>",
    "<PROPERTY_DOC>",
    "<DOC_BEGIN>",
    "<DOC_END>",
    "\"{{{\"",
    "\"}}}\"",
    "<ESCAPED>",
    "<VERBATIM_CONTENT>",
    "<MACRO_START>",
    "<MACRO_END>",
    "<MACRO_CONTENT>",
    "<INFO>",
    "<EXTENSION>",
    "<PARAMS>",
    "<HEADER>",
    "<BR>",
    "<ESCAPE>",
    "<VERBATIM_INLINE>",
    "<REFERENCE>",
    "<HORLINE>",
    "<CELL>",
    "<QUOT_BLOCK>",
    "<QUOT_LINE>",
    "<FORMAT_SYMBOL>",
    "<SPECIAL_SYMBOLS>",
    "<NEW_LINE>",
    "<SPACE>",
    "<SPECIAL_SYMBOL>",
    "<CHAR>",
    "<URI>",
    "<ALPHA>",
    "<DIGIT>",
    "<HEXDIG>",
    "<URI_GEN_DELIMS>",
    "<URI_SUB_DELIMS>",
    "<URI_UNRESERVED>",
    "<URI_RESERVED>",
    "<URI_SCHEME>",
    "<URI_PCT_ENCODED>",
    "<URI_PCHAR>",
    "<URI_QUERY>",
    "<URI_FRAGMENT>",
    "<URI_HIER_PART>",
    "<URI_AUTHORITY>",
    "<URI_USERINFO>",
    "<URI_PATH_ABEMPTY>",
    "<URI_PATH_ABSOLUTE>",
    "<URI_PATH_ROOTLESS>",
    "<URI_SEGMENT>",
    "<URI_SEGMENT_NZ>",
    "<URI_SEGMENT_NZ_NC>",
    "<URI_PORT>",
    "<URI_HOST>",
    "<URI_REG_NAME>",
    "<I_DOC_BEGIN>",
    "<I_DOC_END>",
    "<I_BR>",
    "<I_ESCAPE>",
    "<I_HORLINE>",
    "<I_TABLE_ROW>",
    "<I_TABLE_CELL>",
    "<I_LIST_ITEM>",
    "<I_VERBATIM_INLINE>",
    "<I_VERBATIM_START>",
    "<I_MACRO_BLOCK_START>",
    "<I_MACRO_INLINE_START>",
    "<I_QUOT_BLOCK>",
    "<I_QUOT_LINE>",
    "<I_INFO>",
    "<I_EXTENSION_BLOCK>",
    "<I_EXTENSION_INLINE>",
    "<I_PROPERTY>",
    "<I_PROPERTY_DOC>",
    "<I_PROPERTY_INLINE>",
    "<I_HEADER_BEGIN>",
    "<I_REFERENCE>",
    "<I_HEADER_END>",
    "<I_FORMAT_SYMBOL>",
    "<I_BLOCK_PARAMS>",
    "<I_SPECIAL_SYMBOLS>",
    "<I_URI>",
    "<I_NL>",
    "<I_SPACE>",
    "<I_WORD>",
    "<I_SPECIAL_SYMBOL>",
    "<D_DOC_BEGIN>",
    "<D_DOC_END>",
    "<D_BR>",
    "<D_ESCAPE>",
    "<D_HORLINE>",
    "<D_TABLE_ROW>",
    "<D_TABLE_CELL>",
    "<D_LIST_ITEM>",
    "<D_VERBATIM_INLINE>",
    "<D_VERBATIM_START>",
    "<D_MACRO_BLOCK_START>",
    "<D_MACRO_INLINE_START>",
    "<D_QUOT_BLOCK>",
    "<D_QUOT_LINE>",
    "<D_INFO>",
    "<D_EXTENSION_BLOCK>",
    "<D_EXTENSION_INLINE>",
    "<D_PROPERTY>",
    "<D_PROPERTY_DOC>",
    "<D_PROPERTY_INLINE>",
    "<D_HEADER_BEGIN>",
    "<D_REFERENCE>",
    "<D_HEADER_END>",
    "<D_FORMAT_SYMBOL>",
    "<D_BLOCK_PARAMS>",
    "<D_SPECIAL_SYMBOLS>",
    "<D_URI>",
    "<D_NL>",
    "<D_SPACE>",
    "<D_WORD>",
    "<D_SPECIAL_SYMBOL>",
  };

}
