/* Generated By:JavaCC: Do not edit this line. ConfluenceWikiScannerConstants.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.confluence.javacc;

public interface ConfluenceWikiScannerConstants {

  int EOF = 0;
  int INTERNAL_MACRO = 1;
  int INTERNAL_MACRO_CONTENT = 2;
  int LI = 3;
  int LIST_ITEM = 4;
  int HEADER = 5;
  int VERBATIM = 6;
  int REFERENCE = 7;
  int HORLINE = 8;
  int ESCAPED = 9;
  int BR = 10;
  int CELL = 11;
  int QUOT_BLOCK = 12;
  int QUOT_BLOCK_MACRO = 13;
  int MACRO = 14;
  int MACRO_CONTENT = 15;
  int MACRO_BLOCK = 16;
  int FORMAT_SYMBOL = 17;
  int SPECIAL_SYMBOLS = 18;
  int NEW_LINE = 19;
  int SPACE = 20;
  int SPECIAL_SYMBOL = 21;
  int CHAR = 22;
  int URI = 23;
  int ALPHA = 24;
  int DIGIT = 25;
  int HEXDIG = 26;
  int URI_GEN_DELIMS = 27;
  int URI_SUB_DELIMS = 28;
  int URI_UNRESERVED = 29;
  int URI_RESERVED = 30;
  int URI_SCHEME = 31;
  int URI_SCHEME_COMPOSITE = 32;
  int URI_PCT_ENCODED = 33;
  int URI_PCHAR_FIRST = 34;
  int URI_PCHAR = 35;
  int URI_QUERY = 36;
  int URI_FRAGMENT = 37;
  int URI_HIER_PART = 38;
  int URI_AUTHORITY = 39;
  int URI_USERINFO = 40;
  int URI_PATH_ABEMPTY = 41;
  int URI_PATH_ABSOLUTE = 42;
  int URI_PATH_ROOTLESS = 43;
  int URI_SEGMENT = 44;
  int URI_SEGMENT_NZ = 45;
  int URI_SEGMENT_NZ_NC = 46;
  int URI_PORT = 47;
  int URI_HOST = 48;
  int URI_REG_NAME = 49;
  int I_LIST_ITEM = 50;
  int I_TABLE_ROW = 51;
  int I_HEADER = 52;
  int I_VERBATIM_BLOCK = 53;
  int I_HORLINE = 54;
  int I_VERBATIM_INLINE = 55;
  int I_REFERENCE = 56;
  int I_TABLE_CELL = 57;
  int I_QUOT_BLOCK = 58;
  int I_QUOT_BLOCK_MACRO = 59;
  int I_BR = 60;
  int I_MACRO_BLOCK_START = 61;
  int I_MACRO_EMPTY_BLOCK = 62;
  int I_MACRO_INLINE_START = 63;
  int I_MACRO_EMPTY_INLINE = 64;
  int I_ESCAPED = 65;
  int I_FORMAT_SYMBOL = 66;
  int I_SPECIAL_SYMBOLS = 67;
  int I_URI = 68;
  int I_NL = 69;
  int I_SPACE = 70;
  int I_WORD = 71;
  int I_SPECIAL_SYMBOL = 72;
  int D_LIST_ITEM = 73;
  int D_TABLE_ROW = 74;
  int D_HEADER = 75;
  int D_VERBATIM_BLOCK = 76;
  int D_HORLINE = 77;
  int D_VERBATIM_INLINE = 78;
  int D_REFERENCE = 79;
  int D_TABLE_CELL = 80;
  int D_QUOT_BLOCK = 81;
  int D_QUOT_BLOCK_MACRO = 82;
  int D_BR = 83;
  int D_MACRO_BLOCK_START = 84;
  int D_MACRO_EMPTY_BLOCK = 85;
  int D_MACRO_INLINE_START = 86;
  int D_MACRO_EMPTY_INLINE = 87;
  int D_ESCAPED = 88;
  int D_FORMAT_SYMBOL = 89;
  int D_SPECIAL_SYMBOLS = 90;
  int D_URI = 91;
  int D_NL = 92;
  int D_SPACE = 93;
  int D_WORD = 94;
  int D_SPECIAL_SYMBOL = 95;

  int MACRO_CONTEXT = 0;
  int DEFAULT = 1;
  int INITIAL_CONTEXT = 2;

  String[] tokenImage = {
    "<EOF>",
    "<INTERNAL_MACRO>",
    "<INTERNAL_MACRO_CONTENT>",
    "<LI>",
    "<LIST_ITEM>",
    "<HEADER>",
    "<VERBATIM>",
    "<REFERENCE>",
    "<HORLINE>",
    "<ESCAPED>",
    "\"\\\\\\\\\"",
    "<CELL>",
    "<QUOT_BLOCK>",
    "\"{quote}\"",
    "<MACRO>",
    "<MACRO_CONTENT>",
    "<MACRO_BLOCK>",
    "<FORMAT_SYMBOL>",
    "<SPECIAL_SYMBOLS>",
    "<NEW_LINE>",
    "<SPACE>",
    "<SPECIAL_SYMBOL>",
    "<CHAR>",
    "<URI>",
    "<ALPHA>",
    "<DIGIT>",
    "<HEXDIG>",
    "<URI_GEN_DELIMS>",
    "<URI_SUB_DELIMS>",
    "<URI_UNRESERVED>",
    "<URI_RESERVED>",
    "<URI_SCHEME>",
    "<URI_SCHEME_COMPOSITE>",
    "<URI_PCT_ENCODED>",
    "<URI_PCHAR_FIRST>",
    "<URI_PCHAR>",
    "<URI_QUERY>",
    "<URI_FRAGMENT>",
    "<URI_HIER_PART>",
    "<URI_AUTHORITY>",
    "<URI_USERINFO>",
    "<URI_PATH_ABEMPTY>",
    "<URI_PATH_ABSOLUTE>",
    "<URI_PATH_ROOTLESS>",
    "<URI_SEGMENT>",
    "<URI_SEGMENT_NZ>",
    "<URI_SEGMENT_NZ_NC>",
    "<URI_PORT>",
    "<URI_HOST>",
    "<URI_REG_NAME>",
    "<I_LIST_ITEM>",
    "<I_TABLE_ROW>",
    "<I_HEADER>",
    "<I_VERBATIM_BLOCK>",
    "<I_HORLINE>",
    "<I_VERBATIM_INLINE>",
    "<I_REFERENCE>",
    "<I_TABLE_CELL>",
    "<I_QUOT_BLOCK>",
    "<I_QUOT_BLOCK_MACRO>",
    "<I_BR>",
    "<I_MACRO_BLOCK_START>",
    "<I_MACRO_EMPTY_BLOCK>",
    "<I_MACRO_INLINE_START>",
    "<I_MACRO_EMPTY_INLINE>",
    "<I_ESCAPED>",
    "<I_FORMAT_SYMBOL>",
    "<I_SPECIAL_SYMBOLS>",
    "<I_URI>",
    "<I_NL>",
    "<I_SPACE>",
    "<I_WORD>",
    "<I_SPECIAL_SYMBOL>",
    "<D_LIST_ITEM>",
    "<D_TABLE_ROW>",
    "<D_HEADER>",
    "<D_VERBATIM_BLOCK>",
    "<D_HORLINE>",
    "<D_VERBATIM_INLINE>",
    "<D_REFERENCE>",
    "<D_TABLE_CELL>",
    "<D_QUOT_BLOCK>",
    "<D_QUOT_BLOCK_MACRO>",
    "<D_BR>",
    "<D_MACRO_BLOCK_START>",
    "<D_MACRO_EMPTY_BLOCK>",
    "<D_MACRO_INLINE_START>",
    "<D_MACRO_EMPTY_INLINE>",
    "<D_ESCAPED>",
    "<D_FORMAT_SYMBOL>",
    "<D_SPECIAL_SYMBOLS>",
    "<D_URI>",
    "<D_NL>",
    "<D_SPACE>",
    "<D_WORD>",
    "<D_SPECIAL_SYMBOL>",
  };

}
