/* Generated By:JavaCC: Do not edit this line. XWikiScannerConstants.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.xwiki.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XWikiScannerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTERNAL_VERBATIM_START = 1;
  /** RegularExpression Id. */
  int INTERNAL_VERBATIM_END = 2;
  /** RegularExpression Id. */
  int INTERNAL_VERBATIM_CONTENT = 3;
  /** RegularExpression Id. */
  int INTERNAL_MACRO_START = 4;
  /** RegularExpression Id. */
  int INTERNAL_MACRO_END = 5;
  /** RegularExpression Id. */
  int INTERNAL_MACRO_CONTENT = 6;
  /** RegularExpression Id. */
  int LI = 7;
  /** RegularExpression Id. */
  int HEADER = 8;
  /** RegularExpression Id. */
  int BR = 9;
  /** RegularExpression Id. */
  int DOC_BEGIN = 10;
  /** RegularExpression Id. */
  int DOC_END = 11;
  /** RegularExpression Id. */
  int VERBATIM_START = 12;
  /** RegularExpression Id. */
  int VERBATIM_END = 13;
  /** RegularExpression Id. */
  int VERBATIM_CONTENT = 14;
  /** RegularExpression Id. */
  int MACRO_NAME = 15;
  /** RegularExpression Id. */
  int MACRO_PARAMS = 16;
  /** RegularExpression Id. */
  int MACRO_EMPTY = 17;
  /** RegularExpression Id. */
  int MACRO_START = 18;
  /** RegularExpression Id. */
  int MACRO_END = 19;
  /** RegularExpression Id. */
  int MACRO_CONTENT = 20;
  /** RegularExpression Id. */
  int REFERENCE_IMAGE = 21;
  /** RegularExpression Id. */
  int REFERENCE = 22;
  /** RegularExpression Id. */
  int HORLINE = 23;
  /** RegularExpression Id. */
  int PARAMS = 24;
  /** RegularExpression Id. */
  int CELL = 25;
  /** RegularExpression Id. */
  int QUOT_LINE = 26;
  /** RegularExpression Id. */
  int FORMAT_SYMBOL = 27;
  /** RegularExpression Id. */
  int XWIKI_URI = 28;
  /** RegularExpression Id. */
  int XWIKI_URI_URIS = 29;
  /** RegularExpression Id. */
  int XWIKI_SPECIAL_SYMBOL = 30;
  /** RegularExpression Id. */
  int XWIKI_CHAR = 31;
  /** RegularExpression Id. */
  int XWIKI_SPACE = 32;
  /** RegularExpression Id. */
  int NEW_LINE = 33;
  /** RegularExpression Id. */
  int SPACE = 34;
  /** RegularExpression Id. */
  int SPECIAL_SYMBOL = 35;
  /** RegularExpression Id. */
  int CHAR = 36;
  /** RegularExpression Id. */
  int URI = 37;
  /** RegularExpression Id. */
  int ALPHA = 38;
  /** RegularExpression Id. */
  int DIGIT = 39;
  /** RegularExpression Id. */
  int HEXDIG = 40;
  /** RegularExpression Id. */
  int URI_GEN_DELIMS = 41;
  /** RegularExpression Id. */
  int URI_SUB_DELIMS = 42;
  /** RegularExpression Id. */
  int URI_UNRESERVED = 43;
  /** RegularExpression Id. */
  int URI_RESERVED = 44;
  /** RegularExpression Id. */
  int URI_SCHEME = 45;
  /** RegularExpression Id. */
  int URI_SCHEME_COMPOSITE = 46;
  /** RegularExpression Id. */
  int URI_PCT_ENCODED = 47;
  /** RegularExpression Id. */
  int URI_PCHAR_FIRST = 48;
  /** RegularExpression Id. */
  int URI_PCHAR = 49;
  /** RegularExpression Id. */
  int URI_QUERY = 50;
  /** RegularExpression Id. */
  int URI_FRAGMENT = 51;
  /** RegularExpression Id. */
  int URI_HIER_PART = 52;
  /** RegularExpression Id. */
  int URI_AUTHORITY = 53;
  /** RegularExpression Id. */
  int URI_USERINFO = 54;
  /** RegularExpression Id. */
  int URI_PATH_ABEMPTY = 55;
  /** RegularExpression Id. */
  int URI_PATH_ABSOLUTE = 56;
  /** RegularExpression Id. */
  int URI_PATH_ROOTLESS = 57;
  /** RegularExpression Id. */
  int URI_SEGMENT = 58;
  /** RegularExpression Id. */
  int URI_SEGMENT_NZ = 59;
  /** RegularExpression Id. */
  int URI_SEGMENT_NZ_NC = 60;
  /** RegularExpression Id. */
  int URI_PORT = 61;
  /** RegularExpression Id. */
  int URI_HOST = 62;
  /** RegularExpression Id. */
  int URI_REG_NAME = 63;
  /** RegularExpression Id. */
  int I_DOC_BEGIN = 64;
  /** RegularExpression Id. */
  int I_DOC_END = 65;
  /** RegularExpression Id. */
  int I_LIST_ITEM = 66;
  /** RegularExpression Id. */
  int I_HEADER_BEGIN = 67;
  /** RegularExpression Id. */
  int I_HEADER_END = 68;
  /** RegularExpression Id. */
  int I_HORLINE = 69;
  /** RegularExpression Id. */
  int I_TABLE_ROW = 70;
  /** RegularExpression Id. */
  int I_TABLE_CELL = 71;
  /** RegularExpression Id. */
  int I_REFERENCE = 72;
  /** RegularExpression Id. */
  int I_VERBATIM_START = 73;
  /** RegularExpression Id. */
  int I_MACRO_EMPTY = 74;
  /** RegularExpression Id. */
  int I_MACRO_START = 75;
  /** RegularExpression Id. */
  int I_FORMAT_SYMBOL = 76;
  /** RegularExpression Id. */
  int I_BR = 77;
  /** RegularExpression Id. */
  int I_BLOCK_PARAMS = 78;
  /** RegularExpression Id. */
  int I_INLINE_PARAMS = 79;
  /** RegularExpression Id. */
  int I_QUOT_LINE = 80;
  /** RegularExpression Id. */
  int I_XWIKI_URI = 81;
  /** RegularExpression Id. */
  int I_XWIKI_SPACE = 82;
  /** RegularExpression Id. */
  int I_NL = 83;
  /** RegularExpression Id. */
  int I_WORD = 84;
  /** RegularExpression Id. */
  int I_SPECIAL_SYMBOL = 85;
  /** RegularExpression Id. */
  int D_DOC_BEGIN = 86;
  /** RegularExpression Id. */
  int D_DOC_END = 87;
  /** RegularExpression Id. */
  int D_LIST_ITEM = 88;
  /** RegularExpression Id. */
  int D_HEADER_BEGIN = 89;
  /** RegularExpression Id. */
  int D_HEADER_END = 90;
  /** RegularExpression Id. */
  int D_HORLINE = 91;
  /** RegularExpression Id. */
  int D_TABLE_ROW = 92;
  /** RegularExpression Id. */
  int D_TABLE_CELL = 93;
  /** RegularExpression Id. */
  int D_REFERENCE = 94;
  /** RegularExpression Id. */
  int D_VERBATIM_START = 95;
  /** RegularExpression Id. */
  int D_MACRO_EMPTY = 96;
  /** RegularExpression Id. */
  int D_MACRO_START = 97;
  /** RegularExpression Id. */
  int D_FORMAT_SYMBOL = 98;
  /** RegularExpression Id. */
  int D_BR = 99;
  /** RegularExpression Id. */
  int D_BLOCK_PARAMS = 100;
  /** RegularExpression Id. */
  int D_INLINE_PARAMS = 101;
  /** RegularExpression Id. */
  int D_QUOT_LINE = 102;
  /** RegularExpression Id. */
  int D_XWIKI_URI = 103;
  /** RegularExpression Id. */
  int D_XWIKI_SPACE = 104;
  /** RegularExpression Id. */
  int D_NL = 105;
  /** RegularExpression Id. */
  int D_WORD = 106;
  /** RegularExpression Id. */
  int D_SPECIAL_SYMBOL = 107;

  /** Lexical state. */
  int VERBATIM_CONTEXT = 0;
  /** Lexical state. */
  int MACRO_CONTEXT = 1;
  /** Lexical state. */
  int DEFAULT = 2;
  /** Lexical state. */
  int INITIAL_CONTEXT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<INTERNAL_VERBATIM_START>",
    "<INTERNAL_VERBATIM_END>",
    "<INTERNAL_VERBATIM_CONTENT>",
    "<INTERNAL_MACRO_START>",
    "<INTERNAL_MACRO_END>",
    "<INTERNAL_MACRO_CONTENT>",
    "<LI>",
    "<HEADER>",
    "\"\\\\\\\\\"",
    "<DOC_BEGIN>",
    "<DOC_END>",
    "\"{{{\"",
    "\"}}}\"",
    "<VERBATIM_CONTENT>",
    "<MACRO_NAME>",
    "<MACRO_PARAMS>",
    "<MACRO_EMPTY>",
    "<MACRO_START>",
    "<MACRO_END>",
    "<MACRO_CONTENT>",
    "<REFERENCE_IMAGE>",
    "<REFERENCE>",
    "<HORLINE>",
    "<PARAMS>",
    "<CELL>",
    "<QUOT_LINE>",
    "<FORMAT_SYMBOL>",
    "<XWIKI_URI>",
    "<XWIKI_URI_URIS>",
    "<XWIKI_SPECIAL_SYMBOL>",
    "<XWIKI_CHAR>",
    "<XWIKI_SPACE>",
    "<NEW_LINE>",
    "<SPACE>",
    "<SPECIAL_SYMBOL>",
    "<CHAR>",
    "<URI>",
    "<ALPHA>",
    "<DIGIT>",
    "<HEXDIG>",
    "<URI_GEN_DELIMS>",
    "<URI_SUB_DELIMS>",
    "<URI_UNRESERVED>",
    "<URI_RESERVED>",
    "<URI_SCHEME>",
    "<URI_SCHEME_COMPOSITE>",
    "<URI_PCT_ENCODED>",
    "<URI_PCHAR_FIRST>",
    "<URI_PCHAR>",
    "<URI_QUERY>",
    "<URI_FRAGMENT>",
    "<URI_HIER_PART>",
    "<URI_AUTHORITY>",
    "<URI_USERINFO>",
    "<URI_PATH_ABEMPTY>",
    "<URI_PATH_ABSOLUTE>",
    "<URI_PATH_ROOTLESS>",
    "<URI_SEGMENT>",
    "<URI_SEGMENT_NZ>",
    "<URI_SEGMENT_NZ_NC>",
    "<URI_PORT>",
    "<URI_HOST>",
    "<URI_REG_NAME>",
    "<I_DOC_BEGIN>",
    "<I_DOC_END>",
    "<I_LIST_ITEM>",
    "<I_HEADER_BEGIN>",
    "<I_HEADER_END>",
    "<I_HORLINE>",
    "<I_TABLE_ROW>",
    "<I_TABLE_CELL>",
    "<I_REFERENCE>",
    "<I_VERBATIM_START>",
    "<I_MACRO_EMPTY>",
    "<I_MACRO_START>",
    "<I_FORMAT_SYMBOL>",
    "<I_BR>",
    "<I_BLOCK_PARAMS>",
    "<I_INLINE_PARAMS>",
    "<I_QUOT_LINE>",
    "<I_XWIKI_URI>",
    "<I_XWIKI_SPACE>",
    "<I_NL>",
    "<I_WORD>",
    "<I_SPECIAL_SYMBOL>",
    "<D_DOC_BEGIN>",
    "<D_DOC_END>",
    "<D_LIST_ITEM>",
    "<D_HEADER_BEGIN>",
    "<D_HEADER_END>",
    "<D_HORLINE>",
    "<D_TABLE_ROW>",
    "<D_TABLE_CELL>",
    "<D_REFERENCE>",
    "<D_VERBATIM_START>",
    "<D_MACRO_EMPTY>",
    "<D_MACRO_START>",
    "<D_FORMAT_SYMBOL>",
    "<D_BR>",
    "<D_BLOCK_PARAMS>",
    "<D_INLINE_PARAMS>",
    "<D_QUOT_LINE>",
    "<D_XWIKI_URI>",
    "<D_XWIKI_SPACE>",
    "<D_NL>",
    "<D_WORD>",
    "<D_SPECIAL_SYMBOL>",
  };

}
