/* Generated By:JavaCC: Do not edit this line. XWikiScannerConstants.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.xwiki.javacc;

public interface XWikiScannerConstants {

  int EOF = 0;
  int LI = 1;
  int HEADER = 2;
  int ESCAPE = 3;
  int BR = 4;
  int VERBATIM = 5;
  int REFERENCE = 6;
  int HORLINE = 7;
  int IMAGE = 8;
  int TABLE = 9;
  int CELL = 10;
  int FORMAT_SYMBOL = 11;
  int NEW_LINE = 12;
  int SPACE = 13;
  int SPECIAL_SYMBOL = 14;
  int CHAR = 15;
  int URI = 16;
  int ALPHA = 17;
  int DIGIT = 18;
  int HEXDIG = 19;
  int URI_GEN_DELIMS = 20;
  int URI_SUB_DELIMS = 21;
  int URI_UNRESERVED = 22;
  int URI_RESERVED = 23;
  int URI_SCHEME = 24;
  int URI_PCT_ENCODED = 25;
  int URI_PCHAR = 26;
  int URI_QUERY = 27;
  int URI_FRAGMENT = 28;
  int URI_HIER_PART = 29;
  int URI_AUTHORITY = 30;
  int URI_USERINFO = 31;
  int URI_PATH_ABEMPTY = 32;
  int URI_PATH_ABSOLUTE = 33;
  int URI_PATH_ROOTLESS = 34;
  int URI_SEGMENT = 35;
  int URI_SEGMENT_NZ = 36;
  int URI_PORT = 37;
  int URI_HOST = 38;
  int URI_REG_NAME = 39;
  int I_ESCAPE = 40;
  int I_LIST_ITEM = 41;
  int I_TABLE_DELIMITER = 42;
  int I_HEADER = 43;
  int I_VERBATIM_BLOCK = 44;
  int I_HORLINE = 45;
  int I_REFERENCE = 46;
  int I_TABLE_CELL = 47;
  int I_VERBATIM_INLINE = 48;
  int I_FORMAT_SYMBOL = 49;
  int I_BR = 50;
  int I_URI = 51;
  int I_NL = 52;
  int I_SPACE = 53;
  int I_WORD = 54;
  int I_SPECIAL_SYMBOL = 55;
  int D_ESCAPE = 56;
  int D_LIST_ITEM = 57;
  int D_TABLE_DELIMITER = 58;
  int D_HEADER = 59;
  int D_VERBATIM_BLOCK = 60;
  int D_HORLINE = 61;
  int D_REFERENCE = 62;
  int D_TABLE_CELL = 63;
  int D_VERBATIM_INLINE = 64;
  int D_FORMAT_SYMBOL = 65;
  int D_BR = 66;
  int D_URI = 67;
  int D_NL = 68;
  int D_SPACE = 69;
  int D_WORD = 70;
  int D_SPECIAL_SYMBOL = 71;

  int DEFAULT = 0;
  int INITIAL_CONTEXT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<LI>",
    "<HEADER>",
    "<ESCAPE>",
    "\"\\\\\\\\\"",
    "<VERBATIM>",
    "<REFERENCE>",
    "<HORLINE>",
    "<IMAGE>",
    "<TABLE>",
    "<CELL>",
    "<FORMAT_SYMBOL>",
    "<NEW_LINE>",
    "<SPACE>",
    "<SPECIAL_SYMBOL>",
    "<CHAR>",
    "<URI>",
    "<ALPHA>",
    "<DIGIT>",
    "<HEXDIG>",
    "<URI_GEN_DELIMS>",
    "<URI_SUB_DELIMS>",
    "<URI_UNRESERVED>",
    "<URI_RESERVED>",
    "<URI_SCHEME>",
    "<URI_PCT_ENCODED>",
    "<URI_PCHAR>",
    "<URI_QUERY>",
    "<URI_FRAGMENT>",
    "<URI_HIER_PART>",
    "<URI_AUTHORITY>",
    "<URI_USERINFO>",
    "<URI_PATH_ABEMPTY>",
    "<URI_PATH_ABSOLUTE>",
    "<URI_PATH_ROOTLESS>",
    "<URI_SEGMENT>",
    "<URI_SEGMENT_NZ>",
    "<URI_PORT>",
    "<URI_HOST>",
    "<URI_REG_NAME>",
    "<I_ESCAPE>",
    "<I_LIST_ITEM>",
    "<I_TABLE_DELIMITER>",
    "<I_HEADER>",
    "<I_VERBATIM_BLOCK>",
    "<I_HORLINE>",
    "<I_REFERENCE>",
    "<I_TABLE_CELL>",
    "<I_VERBATIM_INLINE>",
    "<I_FORMAT_SYMBOL>",
    "<I_BR>",
    "<I_URI>",
    "<I_NL>",
    "<I_SPACE>",
    "<I_WORD>",
    "<I_SPECIAL_SYMBOL>",
    "<D_ESCAPE>",
    "<D_LIST_ITEM>",
    "<D_TABLE_DELIMITER>",
    "<D_HEADER>",
    "<D_VERBATIM_BLOCK>",
    "<D_HORLINE>",
    "<D_REFERENCE>",
    "<D_TABLE_CELL>",
    "<D_VERBATIM_INLINE>",
    "<D_FORMAT_SYMBOL>",
    "<D_BR>",
    "<D_URI>",
    "<D_NL>",
    "<D_SPACE>",
    "<D_WORD>",
    "<D_SPECIAL_SYMBOL>",
  };

}
