/* Generated By:JavaCC: Do not edit this line. XWikiScannerConstants.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.xwiki.xwiki20.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XWikiScannerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HEADER_BEGIN = 2;
  /** RegularExpression Id. */
  int LIST_ITEM = 3;
  /** RegularExpression Id. */
  int HORLINE = 4;
  /** RegularExpression Id. */
  int TABLE_ROW = 5;
  /** RegularExpression Id. */
  int PARAMETERS_BEGINNING_OF_LINE = 6;
  /** RegularExpression Id. */
  int BLOCK_PARAMETERS = 7;
  /** RegularExpression Id. */
  int NL_BEGINING_OF_LINE = 8;
  /** RegularExpression Id. */
  int QUOT_LINE_BEGIN = 9;
  /** RegularExpression Id. */
  int TABLE_HCELL = 11;
  /** RegularExpression Id. */
  int TABLE_CELL = 12;
  /** RegularExpression Id. */
  int HEADER_END = 13;
  /** RegularExpression Id. */
  int HEADER_END_INLINE = 14;
  /** RegularExpression Id. */
  int NEW_HEADER_BEGIN = 15;
  /** RegularExpression Id. */
  int INTERNAL_VERBATIM_START = 16;
  /** RegularExpression Id. */
  int VERBATIM_END = 17;
  /** RegularExpression Id. */
  int VERBATIM_CONTENT = 18;
  /** RegularExpression Id. */
  int INTERNAL_MACRO_START = 19;
  /** RegularExpression Id. */
  int MACRO_END = 20;
  /** RegularExpression Id. */
  int MACRO_CONTENT = 21;
  /** RegularExpression Id. */
  int PARAMS = 22;
  /** RegularExpression Id. */
  int HCELL = 23;
  /** RegularExpression Id. */
  int CELL = 24;
  /** RegularExpression Id. */
  int MACRO_NAME = 25;
  /** RegularExpression Id. */
  int MACRO_PARAMS = 26;
  /** RegularExpression Id. */
  int HEADER_BEGIN_PATTERN = 27;
  /** RegularExpression Id. */
  int REFERENCE_IMAGE = 28;
  /** RegularExpression Id. */
  int REFERENCE = 29;
  /** RegularExpression Id. */
  int IMAGE = 30;
  /** RegularExpression Id. */
  int ATTACH = 31;
  /** RegularExpression Id. */
  int XWIKI_URI = 32;
  /** RegularExpression Id. */
  int XWIKI_URI_URIS = 33;
  /** RegularExpression Id. */
  int XWIKI_CHAR = 34;
  /** RegularExpression Id. */
  int EMPTY_LINE = 35;
  /** RegularExpression Id. */
  int NEW_LINE = 36;
  /** RegularExpression Id. */
  int SPACE = 37;
  /** RegularExpression Id. */
  int SPECIAL_SYMBOL = 38;
  /** RegularExpression Id. */
  int CHAR = 39;
  /** RegularExpression Id. */
  int URI = 40;
  /** RegularExpression Id. */
  int ALPHA = 41;
  /** RegularExpression Id. */
  int DIGIT = 42;
  /** RegularExpression Id. */
  int HEXDIG = 43;
  /** RegularExpression Id. */
  int URI_GEN_DELIMS = 44;
  /** RegularExpression Id. */
  int URI_SUB_DELIMS = 45;
  /** RegularExpression Id. */
  int URI_UNRESERVED = 46;
  /** RegularExpression Id. */
  int URI_RESERVED = 47;
  /** RegularExpression Id. */
  int URI_SCHEME = 48;
  /** RegularExpression Id. */
  int URI_SCHEME_COMPOSITE = 49;
  /** RegularExpression Id. */
  int URI_PCT_ENCODED = 50;
  /** RegularExpression Id. */
  int URI_PCHAR_FIRST = 51;
  /** RegularExpression Id. */
  int URI_PCHAR = 52;
  /** RegularExpression Id. */
  int URI_QUERY = 53;
  /** RegularExpression Id. */
  int URI_FRAGMENT = 54;
  /** RegularExpression Id. */
  int URI_HIER_PART = 55;
  /** RegularExpression Id. */
  int URI_AUTHORITY = 56;
  /** RegularExpression Id. */
  int URI_USERINFO = 57;
  /** RegularExpression Id. */
  int URI_PATH_ABEMPTY = 58;
  /** RegularExpression Id. */
  int URI_PATH_ABSOLUTE = 59;
  /** RegularExpression Id. */
  int URI_PATH_ROOTLESS = 60;
  /** RegularExpression Id. */
  int URI_SEGMENT = 61;
  /** RegularExpression Id. */
  int URI_SEGMENT_NZ = 62;
  /** RegularExpression Id. */
  int URI_SEGMENT_NZ_NC = 63;
  /** RegularExpression Id. */
  int URI_PORT = 64;
  /** RegularExpression Id. */
  int URI_HOST = 65;
  /** RegularExpression Id. */
  int URI_REG_NAME = 66;
  /** RegularExpression Id. */
  int DOC_PARAMETERS = 67;
  /** RegularExpression Id. */
  int INLINE_PARAMETERS = 68;
  /** RegularExpression Id. */
  int DOC_BEGIN = 69;
  /** RegularExpression Id. */
  int D_REFERENCE = 70;
  /** RegularExpression Id. */
  int VERBATIM_START = 71;
  /** RegularExpression Id. */
  int MACRO_EMPTY = 72;
  /** RegularExpression Id. */
  int MACRO_START = 73;
  /** RegularExpression Id. */
  int STRONG = 74;
  /** RegularExpression Id. */
  int EM = 75;
  /** RegularExpression Id. */
  int STRIKE = 76;
  /** RegularExpression Id. */
  int INS = 77;
  /** RegularExpression Id. */
  int SUP = 78;
  /** RegularExpression Id. */
  int SUB = 79;
  /** RegularExpression Id. */
  int MONO = 80;
  /** RegularExpression Id. */
  int D_IMAGE = 81;
  /** RegularExpression Id. */
  int D_ATTACH = 82;
  /** RegularExpression Id. */
  int BR = 83;
  /** RegularExpression Id. */
  int D_XWIKI_URI = 84;
  /** RegularExpression Id. */
  int XWIKI_SPACE = 85;
  /** RegularExpression Id. */
  int DOC_END = 86;
  /** RegularExpression Id. */
  int NL = 87;
  /** RegularExpression Id. */
  int WORD = 88;
  /** RegularExpression Id. */
  int XWIKI_SPECIAL_SYMBOL = 89;
  /** RegularExpression Id. */
  int TABLE_END_EMPTY_LINE = 90;
  /** RegularExpression Id. */
  int HEADER_END_EMPTY_LINE = 91;
  /** RegularExpression Id. */
  int BLOCK_END = 92;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int BEGINNING_OF_LINE = 1;
  /** Lexical state. */
  int TABLE_CONTEXT = 2;
  /** Lexical state. */
  int HEADER_CONTEXT = 3;
  /** Lexical state. */
  int VERBATIM_CONTEXT = 4;
  /** Lexical state. */
  int MACRO_CONTEXT = 5;
  /** Lexical state. */
  int INLINE = 6;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\"",
    "<HEADER_BEGIN>",
    "<LIST_ITEM>",
    "<HORLINE>",
    "<TABLE_ROW>",
    "<PARAMETERS_BEGINNING_OF_LINE>",
    "<BLOCK_PARAMETERS>",
    "<NL_BEGINING_OF_LINE>",
    "<QUOT_LINE_BEGIN>",
    "\"\"",
    "<TABLE_HCELL>",
    "<TABLE_CELL>",
    "<HEADER_END>",
    "<HEADER_END_INLINE>",
    "<NEW_HEADER_BEGIN>",
    "<INTERNAL_VERBATIM_START>",
    "\"}}}\"",
    "<VERBATIM_CONTENT>",
    "<INTERNAL_MACRO_START>",
    "<MACRO_END>",
    "<MACRO_CONTENT>",
    "<PARAMS>",
    "<HCELL>",
    "<CELL>",
    "<MACRO_NAME>",
    "<MACRO_PARAMS>",
    "<HEADER_BEGIN_PATTERN>",
    "<REFERENCE_IMAGE>",
    "<REFERENCE>",
    "<IMAGE>",
    "<ATTACH>",
    "<XWIKI_URI>",
    "\"mailto:\"",
    "<XWIKI_CHAR>",
    "<EMPTY_LINE>",
    "<NEW_LINE>",
    "<SPACE>",
    "<SPECIAL_SYMBOL>",
    "<CHAR>",
    "<URI>",
    "<ALPHA>",
    "<DIGIT>",
    "<HEXDIG>",
    "<URI_GEN_DELIMS>",
    "<URI_SUB_DELIMS>",
    "<URI_UNRESERVED>",
    "<URI_RESERVED>",
    "<URI_SCHEME>",
    "<URI_SCHEME_COMPOSITE>",
    "<URI_PCT_ENCODED>",
    "<URI_PCHAR_FIRST>",
    "<URI_PCHAR>",
    "<URI_QUERY>",
    "<URI_FRAGMENT>",
    "<URI_HIER_PART>",
    "<URI_AUTHORITY>",
    "<URI_USERINFO>",
    "<URI_PATH_ABEMPTY>",
    "<URI_PATH_ABSOLUTE>",
    "<URI_PATH_ROOTLESS>",
    "<URI_SEGMENT>",
    "<URI_SEGMENT_NZ>",
    "<URI_SEGMENT_NZ_NC>",
    "<URI_PORT>",
    "<URI_HOST>",
    "<URI_REG_NAME>",
    "<DOC_PARAMETERS>",
    "<INLINE_PARAMETERS>",
    "<DOC_BEGIN>",
    "<D_REFERENCE>",
    "\"{{{\"",
    "<MACRO_EMPTY>",
    "<MACRO_START>",
    "\"**\"",
    "\"//\"",
    "\"--\"",
    "\"__\"",
    "\"^^\"",
    "\",,\"",
    "\"##\"",
    "<D_IMAGE>",
    "<D_ATTACH>",
    "\"\\\\\\\\\"",
    "<D_XWIKI_URI>",
    "<XWIKI_SPACE>",
    "<DOC_END>",
    "<NL>",
    "<WORD>",
    "<XWIKI_SPECIAL_SYMBOL>",
    "<TABLE_END_EMPTY_LINE>",
    "<HEADER_END_EMPTY_LINE>",
    "<BLOCK_END>",
  };

}
