/* Generated By:JavaCC: Do not edit this line. MediawikiScannerConstants.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.mediawiki.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MediawikiScannerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LI_SYMBOL = 1;
  /** RegularExpression Id. */
  int LI = 2;
  /** RegularExpression Id. */
  int HEADER = 3;
  /** RegularExpression Id. */
  int ESCAPE = 4;
  /** RegularExpression Id. */
  int BR = 5;
  /** RegularExpression Id. */
  int VERBATIM_BLOCK = 6;
  /** RegularExpression Id. */
  int VERBATIM_INLINE = 7;
  /** RegularExpression Id. */
  int REFERENCE = 8;
  /** RegularExpression Id. */
  int HORLINE = 9;
  /** RegularExpression Id. */
  int QUOT_LINE = 10;
  /** RegularExpression Id. */
  int PARAMS = 11;
  /** RegularExpression Id. */
  int TABLE_BEGIN = 12;
  /** RegularExpression Id. */
  int TABLE_END = 13;
  /** RegularExpression Id. */
  int TABLE_CAPTION = 14;
  /** RegularExpression Id. */
  int TABLE_ROW = 15;
  /** RegularExpression Id. */
  int TABLE_CELL = 16;
  /** RegularExpression Id. */
  int TABLE_CELL_NL = 17;
  /** RegularExpression Id. */
  int DD = 18;
  /** RegularExpression Id. */
  int FORMAT_SYMBOL = 19;
  /** RegularExpression Id. */
  int MACRO = 20;
  /** RegularExpression Id. */
  int NO_INCLUDE = 21;
  /** RegularExpression Id. */
  int NEW_LINE = 22;
  /** RegularExpression Id. */
  int SPACE = 23;
  /** RegularExpression Id. */
  int SPECIAL_SYMBOL = 24;
  /** RegularExpression Id. */
  int CHAR = 25;
  /** RegularExpression Id. */
  int URI = 26;
  /** RegularExpression Id. */
  int ALPHA = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;
  /** RegularExpression Id. */
  int HEXDIG = 29;
  /** RegularExpression Id. */
  int URI_GEN_DELIMS = 30;
  /** RegularExpression Id. */
  int URI_SUB_DELIMS = 31;
  /** RegularExpression Id. */
  int URI_UNRESERVED = 32;
  /** RegularExpression Id. */
  int URI_RESERVED = 33;
  /** RegularExpression Id. */
  int URI_SCHEME = 34;
  /** RegularExpression Id. */
  int URI_SCHEME_COMPOSITE = 35;
  /** RegularExpression Id. */
  int URI_PCT_ENCODED = 36;
  /** RegularExpression Id. */
  int URI_PCHAR_FIRST = 37;
  /** RegularExpression Id. */
  int URI_PCHAR = 38;
  /** RegularExpression Id. */
  int URI_QUERY = 39;
  /** RegularExpression Id. */
  int URI_FRAGMENT = 40;
  /** RegularExpression Id. */
  int URI_HIER_PART = 41;
  /** RegularExpression Id. */
  int URI_AUTHORITY = 42;
  /** RegularExpression Id. */
  int URI_USERINFO = 43;
  /** RegularExpression Id. */
  int URI_PATH_ABEMPTY = 44;
  /** RegularExpression Id. */
  int URI_PATH_ABSOLUTE = 45;
  /** RegularExpression Id. */
  int URI_PATH_ROOTLESS = 46;
  /** RegularExpression Id. */
  int URI_SEGMENT = 47;
  /** RegularExpression Id. */
  int URI_SEGMENT_NZ = 48;
  /** RegularExpression Id. */
  int URI_SEGMENT_NZ_NC = 49;
  /** RegularExpression Id. */
  int URI_PORT = 50;
  /** RegularExpression Id. */
  int URI_HOST = 51;
  /** RegularExpression Id. */
  int URI_REG_NAME = 52;
  /** RegularExpression Id. */
  int I_ESCAPE = 53;
  /** RegularExpression Id. */
  int I_TABLE_BEGIN = 54;
  /** RegularExpression Id. */
  int I_TABLE_END = 55;
  /** RegularExpression Id. */
  int I_TABLE_CAPTION = 56;
  /** RegularExpression Id. */
  int I_TABLE_ROW = 57;
  /** RegularExpression Id. */
  int I_TABLE_CELL = 58;
  /** RegularExpression Id. */
  int I_TABLE_CELL_NL = 59;
  /** RegularExpression Id. */
  int I_LIST_ITEM = 60;
  /** RegularExpression Id. */
  int I_HEADER_BEGIN = 61;
  /** RegularExpression Id. */
  int I_HORLINE = 62;
  /** RegularExpression Id. */
  int I_REFERENCE = 63;
  /** RegularExpression Id. */
  int I_HEADER_END = 64;
  /** RegularExpression Id. */
  int I_DD = 65;
  /** RegularExpression Id. */
  int I_VERBATIM_BLOCK = 66;
  /** RegularExpression Id. */
  int I_VERBATIM_INLINE = 67;
  /** RegularExpression Id. */
  int I_FORMAT_SYMBOL = 68;
  /** RegularExpression Id. */
  int I_BR = 69;
  /** RegularExpression Id. */
  int I_QUOT_LINE = 70;
  /** RegularExpression Id. */
  int I_MACRO = 71;
  /** RegularExpression Id. */
  int I_NO_INCLUDE = 72;
  /** RegularExpression Id. */
  int I_URI = 73;
  /** RegularExpression Id. */
  int I_NL = 74;
  /** RegularExpression Id. */
  int I_SPACE = 75;
  /** RegularExpression Id. */
  int I_WORD = 76;
  /** RegularExpression Id. */
  int I_SPECIAL_SYMBOL = 77;
  /** RegularExpression Id. */
  int D_ESCAPE = 78;
  /** RegularExpression Id. */
  int D_TABLE_BEGIN = 79;
  /** RegularExpression Id. */
  int D_TABLE_END = 80;
  /** RegularExpression Id. */
  int D_TABLE_CAPTION = 81;
  /** RegularExpression Id. */
  int D_TABLE_ROW = 82;
  /** RegularExpression Id. */
  int D_TABLE_CELL = 83;
  /** RegularExpression Id. */
  int D_TABLE_CELL_NL = 84;
  /** RegularExpression Id. */
  int D_LIST_ITEM = 85;
  /** RegularExpression Id. */
  int D_HEADER_BEGIN = 86;
  /** RegularExpression Id. */
  int D_HORLINE = 87;
  /** RegularExpression Id. */
  int D_REFERENCE = 88;
  /** RegularExpression Id. */
  int D_HEADER_END = 89;
  /** RegularExpression Id. */
  int D_DD = 90;
  /** RegularExpression Id. */
  int D_VERBATIM_BLOCK = 91;
  /** RegularExpression Id. */
  int D_VERBATIM_INLINE = 92;
  /** RegularExpression Id. */
  int D_FORMAT_SYMBOL = 93;
  /** RegularExpression Id. */
  int D_BR = 94;
  /** RegularExpression Id. */
  int D_QUOT_LINE = 95;
  /** RegularExpression Id. */
  int D_MACRO = 96;
  /** RegularExpression Id. */
  int D_NO_INCLUDE = 97;
  /** RegularExpression Id. */
  int D_URI = 98;
  /** RegularExpression Id. */
  int D_NL = 99;
  /** RegularExpression Id. */
  int D_SPACE = 100;
  /** RegularExpression Id. */
  int D_WORD = 101;
  /** RegularExpression Id. */
  int D_SPECIAL_SYMBOL = 102;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INITIAL_CONTEXT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LI_SYMBOL>",
    "<LI>",
    "<HEADER>",
    "<ESCAPE>",
    "<BR>",
    "<VERBATIM_BLOCK>",
    "<VERBATIM_INLINE>",
    "<REFERENCE>",
    "<HORLINE>",
    "<QUOT_LINE>",
    "<PARAMS>",
    "<TABLE_BEGIN>",
    "\"|}\"",
    "<TABLE_CAPTION>",
    "<TABLE_ROW>",
    "<TABLE_CELL>",
    "<TABLE_CELL_NL>",
    "<DD>",
    "<FORMAT_SYMBOL>",
    "<MACRO>",
    "<NO_INCLUDE>",
    "<NEW_LINE>",
    "<SPACE>",
    "<SPECIAL_SYMBOL>",
    "<CHAR>",
    "<URI>",
    "<ALPHA>",
    "<DIGIT>",
    "<HEXDIG>",
    "<URI_GEN_DELIMS>",
    "<URI_SUB_DELIMS>",
    "<URI_UNRESERVED>",
    "<URI_RESERVED>",
    "<URI_SCHEME>",
    "<URI_SCHEME_COMPOSITE>",
    "<URI_PCT_ENCODED>",
    "<URI_PCHAR_FIRST>",
    "<URI_PCHAR>",
    "<URI_QUERY>",
    "<URI_FRAGMENT>",
    "<URI_HIER_PART>",
    "<URI_AUTHORITY>",
    "<URI_USERINFO>",
    "<URI_PATH_ABEMPTY>",
    "<URI_PATH_ABSOLUTE>",
    "<URI_PATH_ROOTLESS>",
    "<URI_SEGMENT>",
    "<URI_SEGMENT_NZ>",
    "<URI_SEGMENT_NZ_NC>",
    "<URI_PORT>",
    "<URI_HOST>",
    "<URI_REG_NAME>",
    "<I_ESCAPE>",
    "<I_TABLE_BEGIN>",
    "<I_TABLE_END>",
    "<I_TABLE_CAPTION>",
    "<I_TABLE_ROW>",
    "<I_TABLE_CELL>",
    "<I_TABLE_CELL_NL>",
    "<I_LIST_ITEM>",
    "<I_HEADER_BEGIN>",
    "<I_HORLINE>",
    "<I_REFERENCE>",
    "<I_HEADER_END>",
    "<I_DD>",
    "<I_VERBATIM_BLOCK>",
    "<I_VERBATIM_INLINE>",
    "<I_FORMAT_SYMBOL>",
    "<I_BR>",
    "<I_QUOT_LINE>",
    "<I_MACRO>",
    "<I_NO_INCLUDE>",
    "<I_URI>",
    "<I_NL>",
    "<I_SPACE>",
    "<I_WORD>",
    "<I_SPECIAL_SYMBOL>",
    "<D_ESCAPE>",
    "<D_TABLE_BEGIN>",
    "<D_TABLE_END>",
    "<D_TABLE_CAPTION>",
    "<D_TABLE_ROW>",
    "<D_TABLE_CELL>",
    "<D_TABLE_CELL_NL>",
    "<D_LIST_ITEM>",
    "<D_HEADER_BEGIN>",
    "<D_HORLINE>",
    "<D_REFERENCE>",
    "<D_HEADER_END>",
    "<D_DD>",
    "<D_VERBATIM_BLOCK>",
    "<D_VERBATIM_INLINE>",
    "<D_FORMAT_SYMBOL>",
    "<D_BR>",
    "<D_QUOT_LINE>",
    "<D_MACRO>",
    "<D_NO_INCLUDE>",
    "<D_URI>",
    "<D_NL>",
    "<D_SPACE>",
    "<D_WORD>",
    "<D_SPECIAL_SYMBOL>",
  };

}
