/* Generated By:JavaCC: Do not edit this line. MediawikiScannerConstants.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.mediawiki.javacc;

public interface MediawikiScannerConstants {

  int EOF = 0;
  int LI_SYMBOL = 1;
  int LI = 2;
  int HEADER = 3;
  int ESCAPE = 4;
  int BR = 5;
  int VERBATIM_BLOCK = 6;
  int VERBATIM_INLINE = 7;
  int REFERENCE = 8;
  int HORLINE = 9;
  int QUOT_LINE = 10;
  int PARAMS = 11;
  int TABLE_BEGIN = 12;
  int TABLE_END = 13;
  int TABLE_CAPTION = 14;
  int TABLE_ROW = 15;
  int TABLE_CELL = 16;
  int TABLE_CELL_NL = 17;
  int DD = 18;
  int FORMAT_SYMBOL = 19;
  int NEW_LINE = 20;
  int SPACE = 21;
  int SPECIAL_SYMBOL = 22;
  int CHAR = 23;
  int URI = 24;
  int ALPHA = 25;
  int DIGIT = 26;
  int HEXDIG = 27;
  int URI_GEN_DELIMS = 28;
  int URI_SUB_DELIMS = 29;
  int URI_UNRESERVED = 30;
  int URI_RESERVED = 31;
  int URI_SCHEME = 32;
  int URI_SCHEME_COMPOSITE = 33;
  int URI_PCT_ENCODED = 34;
  int URI_PCHAR_FIRST = 35;
  int URI_PCHAR = 36;
  int URI_QUERY = 37;
  int URI_FRAGMENT = 38;
  int URI_HIER_PART = 39;
  int URI_AUTHORITY = 40;
  int URI_USERINFO = 41;
  int URI_PATH_ABEMPTY = 42;
  int URI_PATH_ABSOLUTE = 43;
  int URI_PATH_ROOTLESS = 44;
  int URI_SEGMENT = 45;
  int URI_SEGMENT_NZ = 46;
  int URI_SEGMENT_NZ_NC = 47;
  int URI_PORT = 48;
  int URI_HOST = 49;
  int URI_REG_NAME = 50;
  int I_ESCAPE = 51;
  int I_TABLE_BEGIN = 52;
  int I_TABLE_END = 53;
  int I_TABLE_CAPTION = 54;
  int I_TABLE_ROW = 55;
  int I_TABLE_CELL = 56;
  int I_TABLE_CELL_NL = 57;
  int I_LIST_ITEM = 58;
  int I_HEADER_BEGIN = 59;
  int I_HORLINE = 60;
  int I_REFERENCE = 61;
  int I_HEADER_END = 62;
  int I_DD = 63;
  int I_VERBATIM_BLOCK = 64;
  int I_VERBATIM_INLINE = 65;
  int I_FORMAT_SYMBOL = 66;
  int I_BR = 67;
  int I_QUOT_LINE = 68;
  int I_URI = 69;
  int I_NL = 70;
  int I_SPACE = 71;
  int I_WORD = 72;
  int I_SPECIAL_SYMBOL = 73;
  int D_ESCAPE = 74;
  int D_TABLE_BEGIN = 75;
  int D_TABLE_END = 76;
  int D_TABLE_CAPTION = 77;
  int D_TABLE_ROW = 78;
  int D_TABLE_CELL = 79;
  int D_TABLE_CELL_NL = 80;
  int D_LIST_ITEM = 81;
  int D_HEADER_BEGIN = 82;
  int D_HORLINE = 83;
  int D_REFERENCE = 84;
  int D_HEADER_END = 85;
  int D_DD = 86;
  int D_VERBATIM_BLOCK = 87;
  int D_VERBATIM_INLINE = 88;
  int D_FORMAT_SYMBOL = 89;
  int D_BR = 90;
  int D_QUOT_LINE = 91;
  int D_URI = 92;
  int D_NL = 93;
  int D_SPACE = 94;
  int D_WORD = 95;
  int D_SPECIAL_SYMBOL = 96;

  int DEFAULT = 0;
  int INITIAL_CONTEXT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<LI_SYMBOL>",
    "<LI>",
    "<HEADER>",
    "<ESCAPE>",
    "<BR>",
    "<VERBATIM_BLOCK>",
    "<VERBATIM_INLINE>",
    "<REFERENCE>",
    "<HORLINE>",
    "<QUOT_LINE>",
    "<PARAMS>",
    "<TABLE_BEGIN>",
    "\"|}\"",
    "<TABLE_CAPTION>",
    "<TABLE_ROW>",
    "<TABLE_CELL>",
    "<TABLE_CELL_NL>",
    "<DD>",
    "<FORMAT_SYMBOL>",
    "<NEW_LINE>",
    "<SPACE>",
    "<SPECIAL_SYMBOL>",
    "<CHAR>",
    "<URI>",
    "<ALPHA>",
    "<DIGIT>",
    "<HEXDIG>",
    "<URI_GEN_DELIMS>",
    "<URI_SUB_DELIMS>",
    "<URI_UNRESERVED>",
    "<URI_RESERVED>",
    "<URI_SCHEME>",
    "<URI_SCHEME_COMPOSITE>",
    "<URI_PCT_ENCODED>",
    "<URI_PCHAR_FIRST>",
    "<URI_PCHAR>",
    "<URI_QUERY>",
    "<URI_FRAGMENT>",
    "<URI_HIER_PART>",
    "<URI_AUTHORITY>",
    "<URI_USERINFO>",
    "<URI_PATH_ABEMPTY>",
    "<URI_PATH_ABSOLUTE>",
    "<URI_PATH_ROOTLESS>",
    "<URI_SEGMENT>",
    "<URI_SEGMENT_NZ>",
    "<URI_SEGMENT_NZ_NC>",
    "<URI_PORT>",
    "<URI_HOST>",
    "<URI_REG_NAME>",
    "<I_ESCAPE>",
    "<I_TABLE_BEGIN>",
    "<I_TABLE_END>",
    "<I_TABLE_CAPTION>",
    "<I_TABLE_ROW>",
    "<I_TABLE_CELL>",
    "<I_TABLE_CELL_NL>",
    "<I_LIST_ITEM>",
    "<I_HEADER_BEGIN>",
    "<I_HORLINE>",
    "<I_REFERENCE>",
    "<I_HEADER_END>",
    "<I_DD>",
    "<I_VERBATIM_BLOCK>",
    "<I_VERBATIM_INLINE>",
    "<I_FORMAT_SYMBOL>",
    "<I_BR>",
    "<I_QUOT_LINE>",
    "<I_URI>",
    "<I_NL>",
    "<I_SPACE>",
    "<I_WORD>",
    "<I_SPECIAL_SYMBOL>",
    "<D_ESCAPE>",
    "<D_TABLE_BEGIN>",
    "<D_TABLE_END>",
    "<D_TABLE_CAPTION>",
    "<D_TABLE_ROW>",
    "<D_TABLE_CELL>",
    "<D_TABLE_CELL_NL>",
    "<D_LIST_ITEM>",
    "<D_HEADER_BEGIN>",
    "<D_HORLINE>",
    "<D_REFERENCE>",
    "<D_HEADER_END>",
    "<D_DD>",
    "<D_VERBATIM_BLOCK>",
    "<D_VERBATIM_INLINE>",
    "<D_FORMAT_SYMBOL>",
    "<D_BR>",
    "<D_QUOT_LINE>",
    "<D_URI>",
    "<D_NL>",
    "<D_SPACE>",
    "<D_WORD>",
    "<D_SPECIAL_SYMBOL>",
  };

}
