/* Generated By:JavaCC: Do not edit this line. JspWikiScannerConstants.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.jspwiki.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JspWikiScannerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LI_SYMBOL = 1;
  /** RegularExpression Id. */
  int LI = 2;
  /** RegularExpression Id. */
  int HEADER = 3;
  /** RegularExpression Id. */
  int ESCAPE = 4;
  /** RegularExpression Id. */
  int BR = 5;
  /** RegularExpression Id. */
  int VERBATIM = 6;
  /** RegularExpression Id. */
  int VERBATIM_INLINE = 7;
  /** RegularExpression Id. */
  int REFERENCE = 8;
  /** RegularExpression Id. */
  int HORLINE = 9;
  /** RegularExpression Id. */
  int CELL = 10;
  /** RegularExpression Id. */
  int DD = 11;
  /** RegularExpression Id. */
  int FORMAT_SYMBOL = 12;
  /** RegularExpression Id. */
  int NEW_LINE = 13;
  /** RegularExpression Id. */
  int SPACE = 14;
  /** RegularExpression Id. */
  int SPECIAL_SYMBOL = 15;
  /** RegularExpression Id. */
  int CHAR = 16;
  /** RegularExpression Id. */
  int URI = 17;
  /** RegularExpression Id. */
  int ALPHA = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int HEXDIG = 20;
  /** RegularExpression Id. */
  int URI_GEN_DELIMS = 21;
  /** RegularExpression Id. */
  int URI_SUB_DELIMS = 22;
  /** RegularExpression Id. */
  int URI_UNRESERVED = 23;
  /** RegularExpression Id. */
  int URI_RESERVED = 24;
  /** RegularExpression Id. */
  int URI_SCHEME = 25;
  /** RegularExpression Id. */
  int URI_SCHEME_COMPOSITE = 26;
  /** RegularExpression Id. */
  int URI_PCT_ENCODED = 27;
  /** RegularExpression Id. */
  int URI_PCHAR_FIRST = 28;
  /** RegularExpression Id. */
  int URI_PCHAR = 29;
  /** RegularExpression Id. */
  int URI_QUERY = 30;
  /** RegularExpression Id. */
  int URI_FRAGMENT = 31;
  /** RegularExpression Id. */
  int URI_HIER_PART = 32;
  /** RegularExpression Id. */
  int URI_AUTHORITY = 33;
  /** RegularExpression Id. */
  int URI_USERINFO = 34;
  /** RegularExpression Id. */
  int URI_PATH_ABEMPTY = 35;
  /** RegularExpression Id. */
  int URI_PATH_ABSOLUTE = 36;
  /** RegularExpression Id. */
  int URI_PATH_ROOTLESS = 37;
  /** RegularExpression Id. */
  int URI_SEGMENT = 38;
  /** RegularExpression Id. */
  int URI_SEGMENT_NZ = 39;
  /** RegularExpression Id. */
  int URI_SEGMENT_NZ_NC = 40;
  /** RegularExpression Id. */
  int URI_PORT = 41;
  /** RegularExpression Id. */
  int URI_HOST = 42;
  /** RegularExpression Id. */
  int URI_REG_NAME = 43;
  /** RegularExpression Id. */
  int I_ESCAPE = 44;
  /** RegularExpression Id. */
  int I_LIST_ITEM = 45;
  /** RegularExpression Id. */
  int I_TABLE_ROW = 46;
  /** RegularExpression Id. */
  int I_HEADER = 47;
  /** RegularExpression Id. */
  int I_VERBATIM_BLOCK = 48;
  /** RegularExpression Id. */
  int I_HORLINE = 49;
  /** RegularExpression Id. */
  int I_REFERENCE = 50;
  /** RegularExpression Id. */
  int I_TABLE_CELL = 51;
  /** RegularExpression Id. */
  int I_DD = 52;
  /** RegularExpression Id. */
  int I_VERBATIM_INLINE = 53;
  /** RegularExpression Id. */
  int I_FORMAT_SYMBOL = 54;
  /** RegularExpression Id. */
  int I_BR = 55;
  /** RegularExpression Id. */
  int I_URI = 56;
  /** RegularExpression Id. */
  int I_NL = 57;
  /** RegularExpression Id. */
  int I_SPACE = 58;
  /** RegularExpression Id. */
  int I_WORD = 59;
  /** RegularExpression Id. */
  int I_SPECIAL_SYMBOL = 60;
  /** RegularExpression Id. */
  int D_ESCAPE = 61;
  /** RegularExpression Id. */
  int D_LIST_ITEM = 62;
  /** RegularExpression Id. */
  int D_TABLE_ROW = 63;
  /** RegularExpression Id. */
  int D_HEADER = 64;
  /** RegularExpression Id. */
  int D_VERBATIM_BLOCK = 65;
  /** RegularExpression Id. */
  int D_HORLINE = 66;
  /** RegularExpression Id. */
  int D_REFERENCE = 67;
  /** RegularExpression Id. */
  int D_TABLE_CELL = 68;
  /** RegularExpression Id. */
  int D_DD = 69;
  /** RegularExpression Id. */
  int D_VERBATIM_INLINE = 70;
  /** RegularExpression Id. */
  int D_FORMAT_SYMBOL = 71;
  /** RegularExpression Id. */
  int D_BR = 72;
  /** RegularExpression Id. */
  int D_URI = 73;
  /** RegularExpression Id. */
  int D_NL = 74;
  /** RegularExpression Id. */
  int D_SPACE = 75;
  /** RegularExpression Id. */
  int D_WORD = 76;
  /** RegularExpression Id. */
  int D_SPECIAL_SYMBOL = 77;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int INITIAL_CONTEXT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<LI_SYMBOL>",
    "<LI>",
    "<HEADER>",
    "<ESCAPE>",
    "\"\\\\\\\\\"",
    "<VERBATIM>",
    "<VERBATIM_INLINE>",
    "<REFERENCE>",
    "<HORLINE>",
    "<CELL>",
    "<DD>",
    "<FORMAT_SYMBOL>",
    "<NEW_LINE>",
    "<SPACE>",
    "<SPECIAL_SYMBOL>",
    "<CHAR>",
    "<URI>",
    "<ALPHA>",
    "<DIGIT>",
    "<HEXDIG>",
    "<URI_GEN_DELIMS>",
    "<URI_SUB_DELIMS>",
    "<URI_UNRESERVED>",
    "<URI_RESERVED>",
    "<URI_SCHEME>",
    "<URI_SCHEME_COMPOSITE>",
    "<URI_PCT_ENCODED>",
    "<URI_PCHAR_FIRST>",
    "<URI_PCHAR>",
    "<URI_QUERY>",
    "<URI_FRAGMENT>",
    "<URI_HIER_PART>",
    "<URI_AUTHORITY>",
    "<URI_USERINFO>",
    "<URI_PATH_ABEMPTY>",
    "<URI_PATH_ABSOLUTE>",
    "<URI_PATH_ROOTLESS>",
    "<URI_SEGMENT>",
    "<URI_SEGMENT_NZ>",
    "<URI_SEGMENT_NZ_NC>",
    "<URI_PORT>",
    "<URI_HOST>",
    "<URI_REG_NAME>",
    "<I_ESCAPE>",
    "<I_LIST_ITEM>",
    "<I_TABLE_ROW>",
    "<I_HEADER>",
    "<I_VERBATIM_BLOCK>",
    "<I_HORLINE>",
    "<I_REFERENCE>",
    "<I_TABLE_CELL>",
    "<I_DD>",
    "<I_VERBATIM_INLINE>",
    "<I_FORMAT_SYMBOL>",
    "<I_BR>",
    "<I_URI>",
    "<I_NL>",
    "<I_SPACE>",
    "<I_WORD>",
    "<I_SPECIAL_SYMBOL>",
    "<D_ESCAPE>",
    "<D_LIST_ITEM>",
    "<D_TABLE_ROW>",
    "<D_HEADER>",
    "<D_VERBATIM_BLOCK>",
    "<D_HORLINE>",
    "<D_REFERENCE>",
    "<D_TABLE_CELL>",
    "<D_DD>",
    "<D_VERBATIM_INLINE>",
    "<D_FORMAT_SYMBOL>",
    "<D_BR>",
    "<D_URI>",
    "<D_NL>",
    "<D_SPACE>",
    "<D_WORD>",
    "<D_SPECIAL_SYMBOL>",
  };

}
