/* Generated By:JavaCC: Do not edit this line. XWikiScannerConstants.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.xwiki.javacc;

public interface XWikiScannerConstants {

  int EOF = 0;
  int INTERNAL_MACRO_START = 1;
  int INTERNAL_MACRO_END = 2;
  int INTERNAL_MACRO_CONTENT = 3;
  int LI = 4;
  int HEADER = 5;
  int ESCAPE = 6;
  int BR = 7;
  int MACRO_NAME = 8;
  int MACRO_DEF = 9;
  int MACRO_EMPTY = 10;
  int MACRO_START = 11;
  int MACRO_END = 12;
  int MACRO_CONTENT = 13;
  int REFERENCE = 14;
  int HORLINE = 15;
  int TABLE = 16;
  int CELL = 17;
  int FORMAT_SYMBOL = 18;
  int NEW_LINE = 19;
  int SPACE = 20;
  int SPECIAL_SYMBOL = 21;
  int CHAR = 22;
  int URI = 23;
  int ALPHA = 24;
  int DIGIT = 25;
  int HEXDIG = 26;
  int URI_GEN_DELIMS = 27;
  int URI_SUB_DELIMS = 28;
  int URI_UNRESERVED = 29;
  int URI_RESERVED = 30;
  int URI_SCHEME = 31;
  int URI_SCHEME_COMPOSITE = 32;
  int URI_PCT_ENCODED = 33;
  int URI_PCHAR_FIRST = 34;
  int URI_PCHAR = 35;
  int URI_QUERY = 36;
  int URI_FRAGMENT = 37;
  int URI_HIER_PART = 38;
  int URI_AUTHORITY = 39;
  int URI_USERINFO = 40;
  int URI_PATH_ABEMPTY = 41;
  int URI_PATH_ABSOLUTE = 42;
  int URI_PATH_ROOTLESS = 43;
  int URI_SEGMENT = 44;
  int URI_SEGMENT_NZ = 45;
  int URI_SEGMENT_NZ_NC = 46;
  int URI_PORT = 47;
  int URI_HOST = 48;
  int URI_REG_NAME = 49;
  int I_ESCAPE = 50;
  int I_LIST_ITEM = 51;
  int I_TABLE_DELIMITER = 52;
  int I_HEADER = 53;
  int I_HORLINE = 54;
  int I_REFERENCE = 55;
  int I_TABLE_CELL = 56;
  int I_MACRO_EMPTY_BLOCK = 57;
  int I_MACRO_BLOCK_START = 58;
  int I_MACRO_EMPTY_INLINE = 59;
  int I_MACRO_INLINE_START = 60;
  int I_FORMAT_SYMBOL = 61;
  int I_BR = 62;
  int I_URI = 63;
  int I_NL = 64;
  int I_SPACE = 65;
  int I_WORD = 66;
  int I_SPECIAL_SYMBOL = 67;
  int D_ESCAPE = 68;
  int D_LIST_ITEM = 69;
  int D_TABLE_DELIMITER = 70;
  int D_HEADER = 71;
  int D_HORLINE = 72;
  int D_REFERENCE = 73;
  int D_TABLE_CELL = 74;
  int D_MACRO_EMPTY_BLOCK = 75;
  int D_MACRO_BLOCK_START = 76;
  int D_MACRO_EMPTY_INLINE = 77;
  int D_MACRO_INLINE_START = 78;
  int D_FORMAT_SYMBOL = 79;
  int D_BR = 80;
  int D_URI = 81;
  int D_NL = 82;
  int D_SPACE = 83;
  int D_WORD = 84;
  int D_SPECIAL_SYMBOL = 85;

  int MACRO_CONTEXT = 0;
  int DEFAULT = 1;
  int INITIAL_CONTEXT = 2;

  String[] tokenImage = {
    "<EOF>",
    "<INTERNAL_MACRO_START>",
    "<INTERNAL_MACRO_END>",
    "<INTERNAL_MACRO_CONTENT>",
    "<LI>",
    "<HEADER>",
    "<ESCAPE>",
    "\"\\\\\\\\\"",
    "<MACRO_NAME>",
    "<MACRO_DEF>",
    "<MACRO_EMPTY>",
    "<MACRO_START>",
    "<MACRO_END>",
    "<MACRO_CONTENT>",
    "<REFERENCE>",
    "<HORLINE>",
    "<TABLE>",
    "<CELL>",
    "<FORMAT_SYMBOL>",
    "<NEW_LINE>",
    "<SPACE>",
    "<SPECIAL_SYMBOL>",
    "<CHAR>",
    "<URI>",
    "<ALPHA>",
    "<DIGIT>",
    "<HEXDIG>",
    "<URI_GEN_DELIMS>",
    "<URI_SUB_DELIMS>",
    "<URI_UNRESERVED>",
    "<URI_RESERVED>",
    "<URI_SCHEME>",
    "<URI_SCHEME_COMPOSITE>",
    "<URI_PCT_ENCODED>",
    "<URI_PCHAR_FIRST>",
    "<URI_PCHAR>",
    "<URI_QUERY>",
    "<URI_FRAGMENT>",
    "<URI_HIER_PART>",
    "<URI_AUTHORITY>",
    "<URI_USERINFO>",
    "<URI_PATH_ABEMPTY>",
    "<URI_PATH_ABSOLUTE>",
    "<URI_PATH_ROOTLESS>",
    "<URI_SEGMENT>",
    "<URI_SEGMENT_NZ>",
    "<URI_SEGMENT_NZ_NC>",
    "<URI_PORT>",
    "<URI_HOST>",
    "<URI_REG_NAME>",
    "<I_ESCAPE>",
    "<I_LIST_ITEM>",
    "<I_TABLE_DELIMITER>",
    "<I_HEADER>",
    "<I_HORLINE>",
    "<I_REFERENCE>",
    "<I_TABLE_CELL>",
    "<I_MACRO_EMPTY_BLOCK>",
    "<I_MACRO_BLOCK_START>",
    "<I_MACRO_EMPTY_INLINE>",
    "<I_MACRO_INLINE_START>",
    "<I_FORMAT_SYMBOL>",
    "<I_BR>",
    "<I_URI>",
    "<I_NL>",
    "<I_SPACE>",
    "<I_WORD>",
    "<I_SPECIAL_SYMBOL>",
    "<D_ESCAPE>",
    "<D_LIST_ITEM>",
    "<D_TABLE_DELIMITER>",
    "<D_HEADER>",
    "<D_HORLINE>",
    "<D_REFERENCE>",
    "<D_TABLE_CELL>",
    "<D_MACRO_EMPTY_BLOCK>",
    "<D_MACRO_BLOCK_START>",
    "<D_MACRO_EMPTY_INLINE>",
    "<D_MACRO_INLINE_START>",
    "<D_FORMAT_SYMBOL>",
    "<D_BR>",
    "<D_URI>",
    "<D_NL>",
    "<D_SPACE>",
    "<D_WORD>",
    "<D_SPECIAL_SYMBOL>",
  };

}
