/* Generated By:JavaCC: Do not edit this line. XWikiScannerTokenManager.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.xwiki.javacc;
import org.wikimodel.wem.WikiStyle;
import org.wikimodel.wem.impl.IWikiScannerContext;

public class XWikiScannerTokenManager implements XWikiScannerConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjMoveStringLiteralDfa0_0()
{
   return jjMoveNfa_0(0, 0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 178;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff0000ffffd9ffL & l) != 0L)
                  {
                     if (kind > 74)
                        kind = 74;
                     jjCheckNAdd(106);
                  }
                  else if ((0xfc00fffe00000000L & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 72)
                        kind = 72;
                     jjCheckNAddStates(0, 5);
                  }
                  else if ((0x100000200L & l) != 0L)
                  {
                     if (kind > 73)
                        kind = 73;
                     jjCheckNAdd(105);
                  }
                  if (curChar == 13)
                     jjAddStates(6, 11);
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 44;
                  else if (curChar == 42)
                  {
                     if (kind > 69)
                        kind = 69;
                  }
                  break;
               case 1:
                  if ((0xfffffffeffffd9ffL & l) != 0L && kind > 60)
                     kind = 60;
                  break;
               case 4:
               case 5:
                  jjCheckNAddStates(12, 14);
                  break;
               case 11:
               case 13:
               case 16:
               case 18:
               case 21:
               case 25:
                  jjCheckNAddStates(15, 17);
                  break;
               case 41:
                  if (curChar == 42 && kind > 69)
                     kind = 69;
                  break;
               case 44:
                  if (curChar == 45 && kind > 69)
                     kind = 69;
                  break;
               case 45:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 49:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(49, 50);
                  break;
               case 50:
                  if (curChar == 58)
                     jjAddStates(18, 22);
                  break;
               case 52:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(52, 50);
                  break;
               case 53:
                  if (curChar != 47)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(23, 30);
                  break;
               case 54:
                  if ((0x2fff7fd200000000L & l) != 0L)
                     jjCheckNAddStates(31, 33);
                  break;
               case 55:
                  if (curChar == 37)
                     jjCheckNAdd(56);
                  break;
               case 56:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(31, 33);
                  break;
               case 59:
                  if (curChar == 37)
                     jjCheckNAdd(60);
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(34, 39);
                  break;
               case 62:
                  if ((0x2bff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(34, 39);
                  break;
               case 63:
                  if (curChar == 58)
                     jjCheckNAdd(64);
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(40, 43);
                  break;
               case 65:
                  if (curChar != 47)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(44, 48);
                  break;
               case 66:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(44, 48);
                  break;
               case 67:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(44, 48);
                  break;
               case 70:
                  if (curChar != 63)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(49, 51);
                  break;
               case 71:
                  if ((0xafffffd200000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(49, 51);
                  break;
               case 72:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(49, 51);
                  break;
               case 75:
                  if (curChar != 35)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddTwoStates(76, 77);
                  break;
               case 76:
                  if ((0xafffffd200000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddTwoStates(76, 77);
                  break;
               case 77:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 78:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddTwoStates(76, 77);
                  break;
               case 80:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(56, 60);
                  break;
               case 81:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 82:
                  if (curChar != 47)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(52, 55);
                  break;
               case 83:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(56, 60);
                  break;
               case 84:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 86:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(56, 60);
                  break;
               case 87:
                  if (curChar != 47)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(61, 65);
                  break;
               case 88:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(61, 65);
                  break;
               case 89:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 90:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 91:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(61, 65);
                  break;
               case 92:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 93:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 94:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(95, 98);
                  break;
               case 95:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 96:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 97:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(66, 70);
                  break;
               case 98:
                  if ((0x2bff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(66, 70);
                  break;
               case 99:
                  if (curChar != 47)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(71, 75);
                  break;
               case 100:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(71, 75);
                  break;
               case 101:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 102:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 103:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(71, 75);
                  break;
               case 104:
                  if ((0x2bff7fd200000000L & l) != 0L)
                     jjCheckNAddTwoStates(95, 98);
                  break;
               case 105:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAdd(105);
                  break;
               case 106:
                  if ((0x3ff0000ffffd9ffL & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAdd(106);
                  break;
               case 107:
                  if ((0xfc00fffe00000000L & l) != 0L && kind > 75)
                     kind = 75;
                  break;
               case 108:
                  if (curChar == 13)
                     jjAddStates(6, 11);
                  break;
               case 109:
                  if (curChar == 10)
                     jjCheckNAddTwoStates(110, 112);
                  break;
               case 110:
                  if (curChar != 42)
                     break;
                  if (kind > 61)
                     kind = 61;
                  jjCheckNAddTwoStates(110, 111);
                  break;
               case 111:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 61)
                     kind = 61;
                  jjCheckNAdd(111);
                  break;
               case 112:
                  if ((0x2040000000000L & l) != 0L)
                     jjCheckNAddTwoStates(112, 113);
                  break;
               case 113:
                  if (curChar != 46)
                     break;
                  if (kind > 61)
                     kind = 61;
                  jjCheckNAdd(111);
                  break;
               case 114:
                  if (curChar == 10)
                     jjCheckNAdd(127);
                  break;
               case 116:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 117:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 119:
                  if ((0x100000200L & l) != 0L)
                     jjAddStates(76, 78);
                  break;
               case 120:
                  if (curChar == 10 && kind > 62)
                     kind = 62;
                  break;
               case 121:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if ((0x2400L & l) != 0L && kind > 62)
                     kind = 62;
                  break;
               case 128:
                  if (curChar == 10)
                     jjCheckNAdd(129);
                  break;
               case 129:
                  if (curChar != 49)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddTwoStates(130, 131);
                  break;
               case 130:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(130);
                  break;
               case 131:
                  if (curChar == 46)
                     jjCheckNAddStates(79, 83);
                  break;
               case 132:
                  if (curChar != 49)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddTwoStates(130, 133);
                  break;
               case 133:
                  if (curChar == 46)
                     jjCheckNAddStates(84, 87);
                  break;
               case 134:
                  if (curChar != 49)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddTwoStates(130, 135);
                  break;
               case 135:
                  if (curChar == 46)
                     jjCheckNAddStates(88, 90);
                  break;
               case 136:
                  if (curChar != 49)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddTwoStates(130, 137);
                  break;
               case 137:
                  if (curChar == 46)
                     jjCheckNAddTwoStates(138, 140);
                  break;
               case 138:
                  if (curChar != 49)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAddTwoStates(139, 130);
                  break;
               case 139:
                  if (curChar == 46)
                     jjCheckNAdd(140);
                  break;
               case 140:
                  if (curChar != 49)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(130);
                  break;
               case 141:
                  if (curChar == 10)
                     jjCheckNAdd(170);
                  break;
               case 143:
               case 145:
               case 148:
               case 150:
               case 153:
               case 157:
                  jjCheckNAddStates(91, 93);
                  break;
               case 171:
                  if (curChar == 10)
                     jjCheckNAdd(175);
                  break;
               case 172:
                  if (curChar == 45)
                     jjCheckNAdd(173);
                  break;
               case 173:
                  if (curChar != 45)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjCheckNAdd(173);
                  break;
               case 174:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 175:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 176:
                  if (curChar == 10 && kind > 72)
                     kind = 72;
                  break;
               case 177:
                  if ((0x2400L & l) == 0L)
                     break;
                  if (kind > 72)
                     kind = 72;
                  jjCheckNAddStates(0, 5);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x87fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 74)
                        kind = 74;
                     jjCheckNAdd(106);
                  }
                  else if ((0x78000001f8000001L & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(49, 50);
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 46;
                  else if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 42;
                  else if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 39;
                  else if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 37;
                  else if (curChar == 124)
                  {
                     if (kind > 67)
                        kind = 67;
                  }
                  else if (curChar == 91)
                     jjCheckNAddStates(12, 14);
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 7;
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if ((0xffffffffefffffffL & l) != 0L && kind > 60)
                     kind = 60;
                  break;
               case 2:
                  if (curChar == 91)
                     jjCheckNAddStates(12, 14);
                  break;
               case 3:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 4:
                  jjCheckNAddStates(12, 14);
                  break;
               case 5:
                  if ((0xffffffffd7ffffffL & l) != 0L)
                     jjCheckNAddStates(12, 14);
                  break;
               case 6:
                  if (curChar == 93 && kind > 66)
                     kind = 66;
                  break;
               case 7:
                  if (curChar == 124 && kind > 67)
                     kind = 67;
                  break;
               case 8:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 124 && kind > 67)
                     kind = 67;
                  break;
               case 10:
                  if (curChar == 125)
                     jjCheckNAddStates(15, 17);
                  break;
               case 11:
                  if ((0xf7ffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(15, 17);
                  break;
               case 12:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 13:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddStates(15, 17);
                  break;
               case 14:
                  if (curChar == 123)
                     jjAddStates(94, 98);
                  break;
               case 15:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 16:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddStates(15, 17);
                  break;
               case 17:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 18:
                  if ((0xffffffefffffffffL & l) != 0L)
                     jjCheckNAddStates(15, 17);
                  break;
               case 19:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 20:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 21:
                  if ((0xffffffdfffffffffL & l) != 0L)
                     jjCheckNAddStates(15, 17);
                  break;
               case 22:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 23:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 25:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(15, 17);
                  break;
               case 26:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 27:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 125 && kind > 68)
                     kind = 68;
                  break;
               case 30:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 35:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if (curChar == 126 && kind > 69)
                     kind = 69;
                  break;
               case 40:
                  if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 42:
                  if (curChar == 95 && kind > 69)
                     kind = 69;
                  break;
               case 43:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 46:
                  if (curChar == 92 && kind > 70)
                     kind = 70;
                  break;
               case 47:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
               case 49:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(49, 50);
                  break;
               case 51:
               case 52:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(52, 50);
                  break;
               case 54:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(31, 33);
                  break;
               case 56:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 57:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(31, 33);
                  break;
               case 58:
                  if (curChar != 64)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(34, 39);
                  break;
               case 60:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 61:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(34, 39);
                  break;
               case 62:
                  if ((0x47fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(34, 39);
                  break;
               case 66:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(44, 48);
                  break;
               case 68:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 69:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(44, 48);
                  break;
               case 71:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(49, 51);
                  break;
               case 73:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(49, 51);
                  break;
               case 76:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddTwoStates(76, 77);
                  break;
               case 78:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 79:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddTwoStates(76, 77);
                  break;
               case 83:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(56, 60);
                  break;
               case 85:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 86:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(56, 60);
                  break;
               case 88:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(61, 65);
                  break;
               case 90:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 91:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(61, 65);
                  break;
               case 93:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 94:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(95, 98);
                  break;
               case 96:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 97:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(66, 70);
                  break;
               case 98:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(66, 70);
                  break;
               case 100:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(71, 75);
                  break;
               case 102:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 103:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAddStates(71, 75);
                  break;
               case 104:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(95, 98);
                  break;
               case 106:
                  if ((0x87fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAdd(106);
                  break;
               case 107:
                  if ((0x78000001f8000001L & l) != 0L && kind > 75)
                     kind = 75;
                  break;
               case 115:
                  if (curChar == 101)
                     jjCheckNAddTwoStates(116, 118);
                  break;
               case 117:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(117, 118);
                  break;
               case 118:
                  if (curChar != 125)
                     break;
                  if (kind > 62)
                     kind = 62;
                  jjAddStates(76, 78);
                  break;
               case 123:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 124:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 126:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 142:
                  if (curChar == 125)
                     jjCheckNAddStates(91, 93);
                  break;
               case 143:
                  if ((0xf7ffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(91, 93);
                  break;
               case 144:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 145:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddStates(91, 93);
                  break;
               case 146:
                  if (curChar == 123)
                     jjAddStates(99, 103);
                  break;
               case 147:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 148:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddStates(91, 93);
                  break;
               case 149:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 150:
                  if ((0xffffffefffffffffL & l) != 0L)
                     jjCheckNAddStates(91, 93);
                  break;
               case 151:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 152:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 153:
                  if ((0xffffffdfffffffffL & l) != 0L)
                     jjCheckNAddStates(91, 93);
                  break;
               case 154:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 155:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 157:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(91, 93);
                  break;
               case 158:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 156;
                  break;
               case 159:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 160:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 161:
                  if (curChar == 125 && kind > 64)
                     kind = 64;
                  break;
               case 162:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 163:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 167:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 168:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 106:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAdd(106);
                  break;
               case 1:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 60)
                     kind = 60;
                  break;
               case 4:
               case 5:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(12, 14);
                  break;
               case 11:
               case 13:
               case 16:
               case 18:
               case 21:
               case 25:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(15, 17);
                  break;
               case 117:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(104, 105);
                  break;
               case 143:
               case 145:
               case 148:
               case 150:
               case 153:
               case 157:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(91, 93);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 178 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private final int jjMoveStringLiteralDfa0_1()
{
   return jjMoveNfa_1(0, 0);
}
private final int jjMoveNfa_1(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 177;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff0000ffffd9ffL & l) != 0L)
                  {
                     if (kind > 58)
                        kind = 58;
                     jjCheckNAdd(89);
                  }
                  else if ((0xfc00fffe00000000L & l) != 0L)
                  {
                     if (kind > 59)
                        kind = 59;
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     jjCheckNAddStates(106, 111);
                  }
                  else if ((0x100000200L & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAdd(88);
                  }
                  if ((0x2040000000000L & l) != 0L)
                     jjCheckNAddTwoStates(2, 3);
                  else if (curChar == 45)
                     jjCheckNAddTwoStates(142, 176);
                  else if (curChar == 13)
                     jjAddStates(112, 117);
                  if (curChar == 42)
                  {
                     if (kind > 45)
                        kind = 45;
                     jjCheckNAddTwoStates(93, 4);
                  }
                  else if (curChar == 49)
                  {
                     if (kind > 47)
                        kind = 47;
                     jjCheckNAddTwoStates(6, 7);
                  }
                  break;
               case 1:
                  if ((0xfffffffeffffd9ffL & l) != 0L && kind > 44)
                     kind = 44;
                  break;
               case 2:
                  if ((0x2040000000000L & l) != 0L)
                     jjCheckNAddTwoStates(2, 3);
                  break;
               case 3:
                  if (curChar != 46)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAdd(4);
                  break;
               case 4:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAdd(4);
                  break;
               case 5:
                  if (curChar != 49)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddTwoStates(6, 7);
                  break;
               case 6:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAdd(6);
                  break;
               case 7:
                  if (curChar == 46)
                     jjCheckNAddStates(118, 122);
                  break;
               case 8:
                  if (curChar != 49)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddTwoStates(6, 9);
                  break;
               case 9:
                  if (curChar == 46)
                     jjCheckNAddStates(123, 126);
                  break;
               case 10:
                  if (curChar != 49)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddTwoStates(6, 11);
                  break;
               case 11:
                  if (curChar == 46)
                     jjCheckNAddStates(127, 129);
                  break;
               case 12:
                  if (curChar != 49)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddTwoStates(6, 13);
                  break;
               case 13:
                  if (curChar == 46)
                     jjCheckNAddTwoStates(14, 16);
                  break;
               case 14:
                  if (curChar != 49)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddTwoStates(15, 6);
                  break;
               case 15:
                  if (curChar == 46)
                     jjCheckNAdd(16);
                  break;
               case 16:
                  if (curChar != 49)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAdd(6);
                  break;
               case 19:
               case 20:
                  jjCheckNAddStates(130, 132);
                  break;
               case 32:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(32, 33);
                  break;
               case 33:
                  if (curChar == 58)
                     jjAddStates(133, 137);
                  break;
               case 35:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(35, 33);
                  break;
               case 36:
                  if (curChar != 47)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(138, 145);
                  break;
               case 37:
                  if ((0x2fff7fd200000000L & l) != 0L)
                     jjCheckNAddStates(146, 148);
                  break;
               case 38:
                  if (curChar == 37)
                     jjCheckNAdd(39);
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(146, 148);
                  break;
               case 42:
                  if (curChar == 37)
                     jjCheckNAdd(43);
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(149, 154);
                  break;
               case 45:
                  if ((0x2bff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(149, 154);
                  break;
               case 46:
                  if (curChar == 58)
                     jjCheckNAdd(47);
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(155, 158);
                  break;
               case 48:
                  if (curChar != 47)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(159, 163);
                  break;
               case 49:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(159, 163);
                  break;
               case 50:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(159, 163);
                  break;
               case 53:
                  if (curChar != 63)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(164, 166);
                  break;
               case 54:
                  if ((0xafffffd200000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(164, 166);
                  break;
               case 55:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 56:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(164, 166);
                  break;
               case 58:
                  if (curChar != 35)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddTwoStates(59, 60);
                  break;
               case 59:
                  if ((0xafffffd200000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddTwoStates(59, 60);
                  break;
               case 60:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddTwoStates(59, 60);
                  break;
               case 63:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(39, 43);
                  break;
               case 64:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 65:
                  if (curChar != 47)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(167, 170);
                  break;
               case 66:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(171, 175);
                  break;
               case 67:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(171, 175);
                  break;
               case 70:
                  if (curChar != 47)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(176, 180);
                  break;
               case 71:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(176, 180);
                  break;
               case 72:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(176, 180);
                  break;
               case 75:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(78, 81);
                  break;
               case 78:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 80:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(181, 185);
                  break;
               case 81:
                  if ((0x2bff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(181, 185);
                  break;
               case 82:
                  if (curChar != 47)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(186, 190);
                  break;
               case 83:
                  if ((0x2fff7fd200000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(186, 190);
                  break;
               case 84:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 86:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(186, 190);
                  break;
               case 87:
                  if ((0x2bff7fd200000000L & l) != 0L)
                     jjCheckNAddTwoStates(78, 81);
                  break;
               case 88:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(88);
                  break;
               case 89:
                  if ((0x3ff0000ffffd9ffL & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAdd(89);
                  break;
               case 90:
                  if ((0xfc00fffe00000000L & l) != 0L && kind > 59)
                     kind = 59;
                  break;
               case 91:
                  if (curChar == 13)
                     jjAddStates(112, 117);
                  break;
               case 92:
                  if (curChar == 10)
                     jjCheckNAddTwoStates(93, 2);
                  break;
               case 93:
                  if (curChar != 42)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAddTwoStates(93, 4);
                  break;
               case 94:
                  if (curChar == 10)
                     jjCheckNAdd(107);
                  break;
               case 96:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(97, 98);
                  break;
               case 97:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddTwoStates(97, 98);
                  break;
               case 99:
                  if ((0x100000200L & l) != 0L)
                     jjAddStates(191, 193);
                  break;
               case 100:
                  if (curChar == 10 && kind > 46)
                     kind = 46;
                  break;
               case 101:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if ((0x2400L & l) != 0L && kind > 46)
                     kind = 46;
                  break;
               case 108:
                  if (curChar == 10)
                     jjCheckNAdd(5);
                  break;
               case 109:
                  if (curChar == 10)
                     jjCheckNAdd(138);
                  break;
               case 111:
               case 113:
               case 116:
               case 118:
               case 121:
               case 125:
                  jjCheckNAddStates(194, 196);
                  break;
               case 139:
                  if (curChar == 10)
                     jjCheckNAdd(143);
                  break;
               case 140:
                  if (curChar == 45)
                     jjCheckNAdd(141);
                  break;
               case 141:
                  if (curChar != 45)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(141);
                  break;
               case 142:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 143:
                  if (curChar == 45)
                     jjCheckNAdd(142);
                  break;
               case 144:
                  if (curChar == 10 && kind > 56)
                     kind = 56;
                  break;
               case 145:
                  if ((0x2400L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(106, 111);
                  break;
               case 148:
               case 150:
               case 153:
               case 155:
               case 158:
               case 162:
                  jjCheckNAddStates(197, 199);
                  break;
               case 175:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(142, 176);
                  break;
               case 176:
                  if (curChar == 45 && kind > 53)
                     kind = 53;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x87fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 58)
                        kind = 58;
                     jjCheckNAdd(89);
                  }
                  else if ((0x78000001f8000001L & l) != 0L)
                  {
                     if (kind > 59)
                        kind = 59;
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(32, 33);
                  else if (curChar == 123)
                     jjCheckNAddStates(200, 202);
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 29;
                  else if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 27;
                  else if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 25;
                  else if (curChar == 124)
                  {
                     if (kind > 51)
                        kind = 51;
                  }
                  else if (curChar == 91)
                     jjCheckNAddStates(130, 132);
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 22;
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if ((0xffffffffefffffffL & l) != 0L && kind > 44)
                     kind = 44;
                  break;
               case 17:
                  if (curChar == 91)
                     jjCheckNAddStates(130, 132);
                  break;
               case 18:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 19:
                  jjCheckNAddStates(130, 132);
                  break;
               case 20:
                  if ((0xffffffffd7ffffffL & l) != 0L)
                     jjCheckNAddStates(130, 132);
                  break;
               case 21:
                  if (curChar == 93 && kind > 50)
                     kind = 50;
                  break;
               case 22:
                  if (curChar == 124 && kind > 51)
                     kind = 51;
                  break;
               case 23:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 124 && kind > 51)
                     kind = 51;
                  break;
               case 25:
                  if (curChar == 126 && kind > 53)
                     kind = 53;
                  break;
               case 26:
                  if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 95 && kind > 53)
                     kind = 53;
                  break;
               case 28:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 92 && kind > 54)
                     kind = 54;
                  break;
               case 30:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
               case 32:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(32, 33);
                  break;
               case 34:
               case 35:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(35, 33);
                  break;
               case 37:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(146, 148);
                  break;
               case 39:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 40:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(146, 148);
                  break;
               case 41:
                  if (curChar != 64)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(149, 154);
                  break;
               case 43:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 44:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(149, 154);
                  break;
               case 45:
                  if ((0x47fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(149, 154);
                  break;
               case 49:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(159, 163);
                  break;
               case 51:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 52:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(159, 163);
                  break;
               case 54:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(164, 166);
                  break;
               case 56:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 57:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(164, 166);
                  break;
               case 59:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddTwoStates(59, 60);
                  break;
               case 61:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 62:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddTwoStates(59, 60);
                  break;
               case 66:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(171, 175);
                  break;
               case 68:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 69:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(171, 175);
                  break;
               case 71:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(176, 180);
                  break;
               case 73:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(176, 180);
                  break;
               case 76:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 77:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(78, 81);
                  break;
               case 79:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 80:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(181, 185);
                  break;
               case 81:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(181, 185);
                  break;
               case 83:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(186, 190);
                  break;
               case 85:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 86:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(186, 190);
                  break;
               case 87:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(78, 81);
                  break;
               case 89:
                  if ((0x87fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAdd(89);
                  break;
               case 90:
                  if ((0x78000001f8000001L & l) != 0L && kind > 59)
                     kind = 59;
                  break;
               case 95:
                  if (curChar == 101)
                     jjCheckNAddTwoStates(96, 98);
                  break;
               case 97:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(97, 98);
                  break;
               case 98:
                  if (curChar != 125)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjAddStates(191, 193);
                  break;
               case 103:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 104:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 107:
                  if (curChar == 123)
                     jjCheckNAdd(106);
                  break;
               case 110:
                  if (curChar == 125)
                     jjCheckNAddStates(194, 196);
                  break;
               case 111:
                  if ((0xf7ffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(194, 196);
                  break;
               case 112:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 113:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddStates(194, 196);
                  break;
               case 114:
                  if (curChar == 123)
                     jjAddStates(203, 207);
                  break;
               case 115:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 116:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddStates(194, 196);
                  break;
               case 117:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 118:
                  if ((0xffffffefffffffffL & l) != 0L)
                     jjCheckNAddStates(194, 196);
                  break;
               case 119:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 120:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 121:
                  if ((0xffffffdfffffffffL & l) != 0L)
                     jjCheckNAddStates(194, 196);
                  break;
               case 122:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 123:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 125:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(194, 196);
                  break;
               case 126:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 127:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 129:
                  if (curChar == 125 && kind > 48)
                     kind = 48;
                  break;
               case 130:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 135:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 136:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 137:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 138:
                  if (curChar == 123)
                     jjCheckNAdd(137);
                  break;
               case 146:
                  if (curChar == 123)
                     jjCheckNAddStates(200, 202);
                  break;
               case 147:
                  if (curChar == 125)
                     jjCheckNAddStates(197, 199);
                  break;
               case 148:
                  if ((0xf7ffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(197, 199);
                  break;
               case 149:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 150:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddStates(197, 199);
                  break;
               case 151:
                  if (curChar == 123)
                     jjAddStates(208, 212);
                  break;
               case 152:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 153:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddStates(197, 199);
                  break;
               case 154:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 155:
                  if ((0xffffffefffffffffL & l) != 0L)
                     jjCheckNAddStates(197, 199);
                  break;
               case 156:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 157:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 158:
                  if ((0xffffffdfffffffffL & l) != 0L)
                     jjCheckNAddStates(197, 199);
                  break;
               case 159:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 160:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 161:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 162:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(197, 199);
                  break;
               case 163:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 164:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if (curChar == 125 && kind > 52)
                     kind = 52;
                  break;
               case 167:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 168:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 169:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 170:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 171:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 172:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 173:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 89:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAdd(89);
                  break;
               case 1:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 44)
                     kind = 44;
                  break;
               case 19:
               case 20:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(130, 132);
                  break;
               case 97:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(213, 214);
                  break;
               case 111:
               case 113:
               case 116:
               case 118:
               case 121:
               case 125:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(194, 196);
                  break;
               case 148:
               case 150:
               case 153:
               case 155:
               case 158:
               case 162:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(197, 199);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 177 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   110, 112, 127, 129, 170, 175, 109, 114, 128, 141, 171, 176, 3, 5, 6, 11, 
   12, 14, 51, 81, 82, 92, 104, 54, 58, 62, 63, 65, 70, 75, 80, 55, 
   54, 58, 59, 62, 63, 65, 70, 75, 64, 65, 70, 75, 65, 66, 67, 70, 
   75, 71, 72, 75, 83, 84, 70, 75, 83, 84, 87, 70, 75, 87, 88, 89, 
   70, 75, 95, 98, 99, 70, 75, 99, 100, 101, 70, 75, 119, 121, 122, 132, 
   134, 136, 138, 140, 134, 136, 138, 140, 136, 138, 140, 143, 144, 146, 15, 19, 
   23, 28, 33, 147, 151, 155, 160, 165, 117, 118, 93, 2, 107, 5, 138, 143, 
   92, 94, 108, 109, 139, 144, 8, 10, 12, 14, 16, 10, 12, 14, 16, 12, 
   14, 16, 18, 20, 21, 34, 64, 65, 75, 87, 37, 41, 45, 46, 48, 53, 
   58, 63, 38, 37, 41, 42, 45, 46, 48, 53, 58, 47, 48, 53, 58, 48, 
   49, 50, 53, 58, 54, 55, 58, 66, 67, 53, 58, 66, 67, 70, 53, 58, 
   70, 71, 72, 53, 58, 78, 81, 82, 53, 58, 82, 83, 84, 53, 58, 99, 
   101, 102, 111, 112, 114, 148, 149, 151, 106, 137, 174, 115, 119, 123, 128, 133, 
   152, 156, 160, 165, 170, 97, 98, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default : 
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
   "INITIAL_CONTEXT", 
};
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[178];
private final int[] jjstateSet = new int[356];
StringBuffer image;
int jjimageLen;
int lengthOfMatch;
protected char curChar;
public XWikiScannerTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public XWikiScannerTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 178; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 2 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   if (jjmatchedPos < 0)
   {
      if (image == null)
         t.image = "";
      else
         t.image = image.toString();
      t.beginLine = t.endLine = input_stream.getBeginLine();
      t.beginColumn = t.endColumn = input_stream.getBeginColumn();
   }
   else
   {
      String im = jjstrLiteralImages[jjmatchedKind];
      t.image = (im == null) ? input_stream.GetImage() : im;
      t.beginLine = input_stream.getBeginLine();
      t.beginColumn = input_stream.getBeginColumn();
      t.endLine = input_stream.getEndLine();
      t.endColumn = input_stream.getEndColumn();
   }
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = null;
   jjimageLen = 0;

   switch(curLexState)
   {
     case 0:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       jjmatchedKind = 56;
       jjmatchedPos = -1;
       curPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
           matchedToken = jjFillToken();
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default : 
         break;
   }
}
}
